### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

### ISSUE THREAD

**Issue by vpegasus** [microsoft/visual-chatgpt#1]
```shell
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/marvin/projects/visual-chatgpt/visual_chatgpt.py:22 in <module>                            │
│                                                                                                  │
│    19 import numpy as np                                                                         │
│    20 from omegaconf import OmegaConf                                                            │
│    21 from transformers import pipeline, BlipProcessor, BlipForConditionalGeneration, BlipForQ   │
│ ❱  22 import cv2                                                                                 │
│    23 import einops                                                                              │
│    24 from pytorch_lightning import seed_everything                                              │
│    25 import random                                                                              │
│                                                                                                  │
│ /data/data/soft/miniconda3/envs/visgpt/lib/python3.8/site-packages/cv2/__init__.py:5 in <module> │
│                                                                                                  │
│    2 import os                                                                                   │
│    3 import sys                                                                                  │
│    4                                                                                             │
│ ❱  5 from .cv2 import *                                                                          │
│    6 from .data import *                                                                         │
│    7                                                                                             │
│    8 # wildcard import above does not import "private" variables like __version__                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0
```

system:
Linux version 5.15.0-1020-aws (buildd@lcy02-amd64-023) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #24~20.04.1-Ubuntu SMP Fri Sep 2 15:29:13 UTC 2022

how to fix this problem?

**Comment by guidongnan** [comment]
same error and try the cmd and it works for me.
```  
conda install -c anaconda glib

**Comment by vpegasus** [comment]
`conda install -c anaconda glib` works for me.

**Comment by Whiplash-18** [comment]
> same error and try the cmd and it works for me.
> 
> ```
> conda install -c anaconda glib
> ```
Hello, after execute the above command, i met this problem, did you had met it? Thanks!
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮                                                                                       
│ /home/szh/workspace/visual-chatgpt/visual_chatgpt.py:22 in <module>                              │                                                                                       
│                                                                                                  │                                                                                       
│    19 import numpy as np                                                                         │
│    20 from omegaconf import OmegaConf                                                            │
│    21 from transformers import pipeline, BlipProcessor, BlipForConditionalGeneration, BlipForQ   │
│ ❱  22 import cv2                                                                                 │
│    23 import einops                                                                              │
│    24 from pytorch_lightning import seed_everything                                              │
│    25 import random                                                                              │
│                                                                                                  │
│ /home/szh/miniconda3/envs/visgpt/lib/python3.8/site-packages/cv2/__init__.py:5 in <module>       │
│                                                                                                  │
│    2 import os                                                                                   │
│    3 import sys                                                                                  │
│    4                                                                                             │
│ ❱  5 from .cv2 import *                                                                          │
│    6 from .data import *                                                                         │
│    7                                                                                             │
│    8 # wildcard import above does not import "private" variables like __version__                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
