### ISSUE TITLE
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:51837/')

### ISSUE THREAD

**Issue by SherlockZYB** [microsoft/visual-chatgpt#10]
I have followed the README.md to finish all the steps, and I try to run it in the terminal, there is an error.
System: Ubuntu 20.04.5 LTS 64-bit

python visual_chatgpt.py

Traceback (most recent call last):
  File "visual_chatgpt.py", line 5, in <module>
    import gradio as gr
  File "/home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/gradio/components.py", line 32, in <module>
    from gradio import media_data, processing_utils, utils
  File "/home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/gradio/processing_utils.py", line 25, in <module>
    from gradio import encryptor, utils
  File "/home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/gradio/utils.py", line 454, in <module>
    class AsyncRequest:
  File "/home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/gradio/utils.py", line 474, in AsyncRequest
    client = httpx.AsyncClient()
  File "/home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/httpx/_client.py", line 1398, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "/home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/httpx/_client.py", line 218, in _get_proxy_map
    return {
  File "/home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/httpx/_client.py", line 219, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/httpx/_config.py", line 333, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:51837/')

**Comment by CODINNLG** [comment]
Hi, this is a common issue, and you can fix this problem by utilizing another port, e.g.,127.0.0.1:6850.

**Comment by ShengmingYin01** [comment]
[https://github.com/lllyasviel/ControlNet/issues/182](url) 

It seems like the same issue as you met when ""**import gradio as gr**""

Maybe you can try to close the network proxy in the system settings, and restart a new terminal to run the comand. Thanks~

**Comment by SherlockZYB** [comment]
Ok, thanks, but I got a new problem, and I didn't find the way to solve it, it seems to have something to do with the system?

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /mnt/data1/ZhouFF/visual-chatgpt-main/visual_chatgpt.py:22 in <module>       │
│                                                                              │
│    19 import numpy as np                                                     │
│    20 from omegaconf import OmegaConf                                        │
│    21 from transformers import pipeline, BlipProcessor, BlipForConditionalGe │
│ ❱  22 import cv2                                                             │
│    23 import einops                                                          │
│    24 from pytorch_lightning import seed_everything                          │
│    25 import random                                                          │
│                                                                              │
│ /home/ubuntu/miniconda3/envs/visgpt/lib/python3.8/site-packages/cv2/__init__ │
│ .py:5 in <module>                                                            │
│                                                                              │
│    2 import os                                                               │
│    3 import sys                                                              │
│    4                                                                         │
│ ❱  5 from .cv2 import *                                                      │
│    6 from .data import *                                                     │
│    7                                                                         │
│    8 # wildcard import above does not import "private" variables like __vers │
╰──────────────────────────────────────────────────────────────────────────────╯
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: 
ffi_type_uint32, version LIBFFI_BASE_7.0

**Comment by WenB777** [comment]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/yanwenbiao/CODE/visual-chatgpt-main/visual_chatgpt.py:22 in <module>                       │
│                                                                                                  │
│    19 import numpy as np                                                                         │
│    20 from omegaconf import OmegaConf                                                            │
│    21 from transformers import pipeline, BlipProcessor, BlipForConditionalGeneration, BlipForQ   │
│ ❱  22 import cv2                                                                                 │
│    23 import einops                                                                              │
│    24 from pytorch_lightning import seed_everything                                              │
│    25 import random                                                                              │
│                                                                                                  │
│ /home/yanwenbiao/anaconda3/envs/visgpt/lib/python3.8/site-packages/cv2/__init__.py:5 in <module> │
│                                                                                                  │
│    2 import os                                                                                   │
│    3 import sys                                                                                  │
│    4                                                                                             │
│ ❱  5 from .cv2 import *                                                                          │
│    6 from .data import *                                                                         │
│    7                                                                                             │
│    8 # wildcard import above does not import "private" variables like __version__                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0
I got the problem too.

**Comment by ShengmingYin01** [comment]
[https://github.com/microsoft/visual-chatgpt/issues/29](url)

It seems like the problem you met.

Maybe **pip install opencv-python==4.5.1.48** can help you~
