### ISSUE TITLE
bash download.sh适用于 Linux 的 Windows 子系统没有已安装的分发版

### ISSUE THREAD

**Issue by 77LJH** [microsoft/visual-chatgpt#100]
(visgpt) PS D:\IDM\IDM_download\压缩文件\visual-chatgpt-main\visual-chatgpt-main> bash download.sh
适用于 Linux 的 Windows 子系统没有已安装的分发版。
可以通过访问 Microsoft Store 来安装分发版:

我去微软商店获取ubuntu后，打开Ubuntu的终端后按任意键直接闪退了

**Comment by tiiime** [comment]
这个脚本只是 clone 了 ControlNet，然后到 huggingface 下载模型，没必要搞个 wsl 跑，自己手动操作下就行。

**Comment by 77LJH** [comment]
@tiiime 这要怎么手动操作呢？
![image](https://user-images.githubusercontent.com/104681814/224522591-0a3760f3-e201-4311-a5a2-62ed506faf3f.png)

**Comment by wrk226** [comment]
都玩visual-chatgpt了，遇到问题还不知道问chatgpt吗？`ln`是linux上创建软连接的命令，换到windows上就是`mklink /D ldm ControlNet\ldm`
