### ISSUE TITLE
pip install 阶段:卡在最后一个包,这是什么原因导致的？

### ISSUE THREAD

**Issue by Bestboy125** [microsoft/visual-chatgpt#118]
![image](https://user-images.githubusercontent.com/41653408/224540702-4c297bc0-9b83-453f-95be-b9eb15774abc.png)
![image](https://user-images.githubusercontent.com/41653408/224540725-e6b480dd-7d67-4912-a454-ffe7a04bb2f5.png)
各位大佬帮小弟解决一下 Thanks♪(･ω･)ﾉ

**Comment by wrk226** [comment]
多等一会就行了

**Comment by Bestboy125** [comment]
好的，感谢回复，我再等等看，目前还没好。

**Comment by Bestboy125** [comment]
> 多等一会就行了


好的，感谢回复，我再等等看，目前还没好。

**Comment by mupanpan** [comment]
我最后basicsr安装失败，无法安装。我CPU是AMD的。

**Comment by wrk226** [comment]
我CPU也是AMD的，5950X，这有什么关系

**Comment by yunfengsay** [comment]
直接手动下载whl到本地 然后pip 安装

**Comment by Bestboy125** [comment]
> 直接手动下载whl到本地 然后pip 安装

感谢，问题已解决
