### ISSUE TITLE
ERROR: No matching distribution found for opencv-contrib-python==4.3.0.36

### ISSUE THREAD

**Issue by yundaehyuck** [microsoft/visual-chatgpt#125]
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==4.3.0.36 (from versions: 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.15.55, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72)
ERROR: No matching distribution found for opencv-contrib-python==4.3.0.36

I think "opencv-contrib-python==4.3.0.36" don't exist.

**Comment by sinwoobang** [comment]
I have tried resolving it by following Dockerfile commands. Still testing it. It is just for your information.

```
RUN pip install --upgrade pip
RUN pip install opencv-python
RUN sed '/opencv/d' requirement.txt > requirement.txt
RUN pip install -r requirement.txt
```

**Comment by sinwoobang** [comment]
It looks related to https://github.com/microsoft/visual-chatgpt/issues/50.

**Comment by yundaehyuck** [comment]
@sinwoobang Thank you for your reply!

**Comment by baipengfeifei** [comment]
> sed '/opencv/d' requirement.txt > requirement.txt
after doing this,the problem is WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv,so what can i do to solve it?Thank you!
