### ISSUE TITLE
Running the demo in low GPU memory PC.

### ISSUE THREAD

**Issue by chrsas** [microsoft/visual-chatgpt#126]
In Stable Diffusion, there are 3 parameters which like `--lowvram` `--medvram` `--xformers` for low Vram PC to run, does Visual ChatGpt have these parameters, and how to use them?

**Comment by xkpeknghq2035** [comment]
I don't familiar with Python, so I enable the low memory module in the code hardly.

`ImageEditing.____init__`
```python
sd_model = StableDiffusionInpaintPipeline.from_pretrained("runwayml/stable-diffusion-inpainting",)
sd_model.enable_model_cpu_offload()
sd_model.enable_xformers_memory_efficient_attention()
self.inpainting = sd_model.to("cpu")
```
`T2I__init__`
```python
self.pipe.enable_model_cpu_offload()
self.pipe.enable_xformers_memory_efficient_attention()
self.pipe.to("cpu")
```
`ImageCaptioning.__init__`
```python
self.model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to("cpu")
```
Write other models in the similar way.

My PC has 32G memory and the GPU has 6G memory, so it can load about 5 models.

**Comment by chrsas** [comment]
I don't familiar with Python, so I enable the low memory module in the code hardly.

`ImageEditing.____init__`
```python
sd_model = StableDiffusionInpaintPipeline.from_pretrained("runwayml/stable-diffusion-inpainting",)
sd_model.enable_model_cpu_offload()
sd_model.enable_xformers_memory_efficient_attention()
self.inpainting = sd_model.to("cpu")
```
`T2I.__init__`
```python
self.pipe.enable_model_cpu_offload()
self.pipe.enable_xformers_memory_efficient_attention()
self.pipe.to("cpu")
```
`ImageCaptioning.__init__`
```python
self.model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to("cpu")
```
Write other models in the similar way.

My PC has 32G memory and the GPU has 6G memory, so it can load about 5 models.
