### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by drammen94** [microsoft/visual-chatgpt#13]
Hi,

Im getting the following error:

│ C:\Users\Jan\anaconda3\envs\visgpt\lib\site-packages\torch\cuda\__init__.py:211 in _lazy_init    │
│                                                                                                  │
│   208 │   │   │   │   "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "        │
│   209 │   │   │   │   "multiprocessing, you must use the 'spawn' start method")                  │
│   210 │   │   if not hasattr(torch._C, '_cuda_getDeviceCount'):                                  │
│ ❱ 211 │   │   │   raise AssertionError("Torch not compiled with CUDA enabled")                   │
│   212 │   │   if _cudart is None:                                                                │
│   213 │   │   │   raise AssertionError(                                                          │
│   214 │   │   │   │   "libcudart functions unavailable. It looks like you have a broken build?   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Torch not compiled with CUDA enabled

Which CUDA do i need?

**Comment by b2zer** [comment]
According to requirements.txt:

torch==1.12.1
torchvision==0.13.1

See: https://pytorch.org/get-started/previous-versions/

e.g.: 
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch

**Comment by Fenfel** [comment]
> According to requirements.txt:
> 
> torch==1.12.1 torchvision==0.13.1
> 
> See: https://pytorch.org/get-started/previous-versions/
> 
> e.g.: conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch

not working 

AssertionError: Torch not compiled with CUDA enabled

(visgpt) C:\Users\anton\Desktop\SD\visual-gpt\visual-chatgpt>
(visgpt) C:\Users\anton\Desktop\SD\visual-gpt\visual-chatgpt>
(visgpt) C:\Users\anton\Desktop\SD\visual-gpt\visual-chatgpt>
(visgpt) C:\Users\anton\Desktop\SD\visual-gpt\visual-chatgpt>
(visgpt) C:\Users\anton\Desktop\SD\visual-gpt\visual-chatgpt>conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done

 All requested packages already installed.
