### ISSUE TITLE
dash download.sh   wget: not found

### ISSUE THREAD

**Issue by XIE-create0** [microsoft/visual-chatgpt#142]
<img width="557" alt="截屏2023-03-13 10 47 00" src="https://user-images.githubusercontent.com/127460399/224596766-e9e9863c-b173-40f0-ba59-e17ebf7552da.png">
 I already installed wdet

**Comment by yunfengsay** [comment]
brew install wget

**Comment by yunfengsay** [comment]
你试试你本地环境中能调用到wget吗 这是你自己的环境问题

**Comment by K-tang-mkv** [comment]
install wget first

**Comment by lucienshawls** [comment]
如果你有专业下载工具的话（如：IDM），我不建议你用wget下载，因为这些文件每个都大于5GB，用命令行下载的速度肯定不如用专业下载工具下载的速度快。
如果你用下载工具下载的话，每行链接都是一个文件的下载地址，下载好以后把这8个文件放到ControlNet/models文件夹下就可以了。

**Comment by ejums** [comment]
> 

的确， 文件太大了

**Comment by chenfei-wu** [comment]
We removed download.sh in the latest version. Please try the new version.
