### ISSUE TITLE
how to add negative prompt

### ISSUE THREAD

**Issue by zhouzhengguang** [microsoft/visual-chatgpt#144]
Excellent work!
Is there any way to add negative prompt/text to help text2image get better?

**Comment by Wang-Xiaodong1899** [comment]
Hi @zhouzhengguang , we have updated a new version. And you can add the negative prompts to the line https://github.com/microsoft/visual-chatgpt/blob/main/visual_chatgpt.py#L230 to improve the Text2Image.

Thanks~

**Comment by zhouzhengguang** [comment]
Thanks, that's great!
