### ISSUE TITLE
如何改变图片分辨率从512到1024

### ISSUE THREAD

**Issue by amazing-fish** [microsoft/visual-chatgpt#145]
发布的图片都是512*512的，在哪个文件中修改可以得到其它分辨率的图像呢，我尝试把运行py里的512都改成了1024但是只能使最后显示画框变大

**Comment by K-tang-mkv** [comment]
和gradio框架有关吗，它负责前端图片的渲染，这是我的猜测

**Comment by tsogzark** [comment]
https://huggingface.co/blog/stable_diffusion#:~:text=By%20default%2C%20stable%20diffusion%20produces%20images%20of%20512%20%C3%97%20512%20pixels.

```
image = self.pipe(prompt, negative_prompt=self.n_prompt, height=1024, width=1024).images[0]
```
