### ISSUE TITLE
MacOS M1 16 Ram 環境可以部署嗎？

### ISSUE THREAD

**Issue by wastu01** [microsoft/visual-chatgpt#149]
不知有無支援

**Comment by chiyagao** [comment]
同问，求踢

**Comment by berry807** [comment]
Read this comment for Mac support: https://github.com/microsoft/visual-chatgpt/issues/37#issuecomment-1465469089

**Comment by wastu01** [comment]
# Advice for 4 Tesla V100 32GB  
what is that "Tesla V100" mean ?
I am using macOS M1 8 Ram have enough space

**Comment by wastu01** [comment]
請問

> 可以安装，已成功运行！

好，我安裝試試看

**Comment by wastu01** [comment]
我的學習筆記：https://hackmd.io/@DCT/Visual-ChatGPT

**Comment by wastu01** [comment]
@Designdocs 想詢問不是用 N卡依舊是用下列程式嗎？

# Advice for CPU Users
python visual_chatgpt.py --load ImageCaptioning_cpu,Text2Image_cpu

# Advice for 1 Tesla T4 15GB  (Google Colab)                       
python visual_chatgpt.py --load "ImageCaptioning_cuda:0,Text2Image_cuda:0"
                                
# Advice for 4 Tesla V100 32GB                            
python visual_chatgpt.py --load "ImageCaptioning_cuda:0,ImageEditing_cuda:0,
    Text2Image_cuda:1,Image2Canny_cpu,CannyText2Image_cuda:1,
    Image2Depth_cpu,DepthText2Image_cuda:1,VisualQuestionAnswering_cuda:2,
    InstructPix2Pix_cuda:2,Image2Scribble_cpu,ScribbleText2Image_cuda:2,
    Image2Seg_cpu,SegText2Image_cuda:2,Image2Pose_cpu,PoseText2Image_cuda:2,
    Image2Hed_cpu,HedText2Image_cuda:3,Image2Normal_cpu,
    NormalText2Image_cuda:3,Image2Line_cpu,LineText2Image_cuda:3"

**Comment by wastu01** [comment]
有人成功在 Safari 上成功運行嗎？
My situation can not open link on Safari in 0.0.0.0:7868/

**Comment by wastu01** [comment]
> 可以安装，已成功运行！

想問能成功執行圖片編輯處理嗎？
我遇到以下錯誤

```
UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
warnings.warn('resource_tracker: There appear to be %d ’
```

**Comment by wastu01** [comment]
can not create a image using text. 
I think Text2Image_cpu is not install successfully.
python3 visual_chatgpt.py --load ImageCaptioning_cpu,ImageEditing_cpu,Text2Image_cpu           

How can I reinstall  visual foundation model ?

**Comment by wuliwuxin** [comment]
> 有人成功在 Safari 上成功運行嗎？ My situation can not open link on Safari in 0.0.0.0:7868/

 Safari 上可以换成  http://localhost:7868/，运行成功了

**Comment by wastu01** [comment]
ok I go to close this issue
