### ISSUE TITLE
huggingface.co error 404 not found?

### ISSUE THREAD

**Issue by itsWinwin** [microsoft/visual-chatgpt#16]
Hi! Love this project, but I'm running into a small problem when trying to install. Any idea how to fix it? Thank you. =)

_#The problem:_

(visgpt) C:\Users\myuser\visual-chatgpt>bash download.sh
Cloning into 'ControlNet'...
remote: Enumerating objects: 1258, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 1258 (delta 2), reused 3 (delta 1), pack-reused 1252
Receiving objects: 100% (1258/1258), 122.36 MiB | 4.58 MiB/s, done.
Resolving deltas: 100% (543/543), done.
Updating files: 100% (505/505), done.
download.sh: line 5: cd: $'ControlNet/models\r': No such file or directory
--2023-03-09 17:37:08--  https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_canny.pth%0D
Resolving huggingface.co (huggingface.co)... 3.231.67.228, 54.235.118.239, 2600:1f18:147f:e800:671:b733:ecf3:a585, ...
Connecting to huggingface.co (huggingface.co)|3.231.67.228|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-09 17:37:09 ERROR 404: Not Found.

--2023-03-09 17:37:09--  https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_depth.pth%0D
Resolving huggingface.co (huggingface.co)... 3.231.67.228, 54.235.118.239, 2600:1f18:147f:e800:671:b733:ecf3:a585, ...
Connecting to huggingface.co (huggingface.co)|3.231.67.228|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-09 17:37:09 ERROR 404: Not Found.

--2023-03-09 17:37:09--  https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_hed.pth%0D
Resolving huggingface.co (huggingface.co)... 3.231.67.228, 54.235.118.239, 2600:1f18:147f:e800:671:b733:ecf3:a585, ...
Connecting to huggingface.co (huggingface.co)|3.231.67.228|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-09 17:37:10 ERROR 404: Not Found.

--2023-03-09 17:37:10--  https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_mlsd.pth%0D
Resolving huggingface.co (huggingface.co)... 3.231.67.228, 54.235.118.239, 2600:1f18:147f:e800:671:b733:ecf3:a585, ...
Connecting to huggingface.co (huggingface.co)|3.231.67.228|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-09 17:37:10 ERROR 404: Not Found.

--2023-03-09 17:37:10--  https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_normal.pth%0D
Resolving huggingface.co (huggingface.co)... 3.231.67.228, 54.235.118.239, 2600:1f18:147f:e800:671:b733:ecf3:a585, ...
Connecting to huggingface.co (huggingface.co)|3.231.67.228|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-09 17:37:11 ERROR 404: Not Found.

--2023-03-09 17:37:11--  https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_openpose.pth%0D
Resolving huggingface.co (huggingface.co)... 3.231.67.228, 54.235.118.239, 2600:1f18:147f:e800:671:b733:ecf3:a585, ...
Connecting to huggingface.co (huggingface.co)|3.231.67.228|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-09 17:37:11 ERROR 404: Not Found.

--2023-03-09 17:37:11--  https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_scribble.pth%0D
Resolving huggingface.co (huggingface.co)... 3.231.67.228, 54.235.118.239, 2600:1f18:147f:e800:671:b733:ecf3:a585, ...
Connecting to huggingface.co (huggingface.co)|3.231.67.228|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-09 17:37:12 ERROR 404: Not Found.

--2023-03-09 17:37:12--  https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_seg.pth%0D
Resolving huggingface.co (huggingface.co)... 3.231.67.228, 54.235.118.239, 2600:1f18:147f:e800:671:b733:ecf3:a585, ...
Connecting to huggingface.co (huggingface.co)|3.231.67.228|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-09 17:37:12 ERROR 404: Not Found.

download.sh: line 14: cd: $'../../\r': No such file or directory

**Comment by Wang-Xiaodong1899** [comment]
There seems to be something wrong with the commands you executed, eg 'cd ControlNet/models\r', error of extra '\r', and error of '%0D' after weight path. You can fix it by running the commands in download.sh line by line.

Thanks~

**Comment by itsWinwin** [comment]
Thank you! =)
