### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by miitchel** [microsoft/visual-chatgpt#160]
I'm getting this error, using the new installation process.

```
RuntimeError: CUDA out of memory. Tried to allocate 146.00 MiB (GPU 0; 8.00 GiB total capacity; 7.10 GiB already allocated; 0 bytes free; 7.30 GiB reserved in total by
PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and
PYTORCH_CUDA_ALLOC_CONF
```

Windows 11 WSL Ubuntu 20.04.5 LTS

**Comment by chenfei-wu** [comment]
Hi @miitchel,

Please share your cmd to run the code, for example, `python visual_chatgpt.py --load ImageCaptioning_cpu`

**Comment by miitchel** [comment]
I'm just using `python visual_chatgpt.py` since I don't want to use CPU for this, is that bad?

**Comment by chenfei-wu** [comment]
How about `python visual_chatgpt.py --load "ImageCaptioning_cuda:0,Text2Image_cuda:0"`?

**Comment by miitchel** [comment]
That works, thanks!
