### ISSUE TITLE
Local server url

### ISSUE THREAD

**Issue by videscar** [microsoft/visual-chatgpt#162]
I am having problems getting access to the generated link. When I copy it in the browser it says that is not available.

I am running on windows... any idea how to solve it?

The programm seems to run perfect, loading the models on the gpu without problem but I can't visualize it.

Thanks!

**Comment by mikesoes** [comment]
same here, any ideas?

**Comment by 21pl** [comment]
use the default stable diffusion ui one

http://127.0.0.1:7860/

**Comment by mikesoes** [comment]
http://127.0.0.1:7861/ worked!

**Comment by dzid26** [comment]
http://localhost:7861/ and http://127.0.0.1:7861/ work. 

http://0.0.0.0:7861/ doesn't work. At least on Windows.
