### ISSUE TITLE
The output is not closely what is expected - what am I doing wrong?

### ISSUE THREAD

**Issue by emarutian** [microsoft/visual-chatgpt#166]
Running on Google's Colab... Here is the output I am getting for sample queries:
![2023-03-13_11-08-11](https://user-images.githubusercontent.com/1533929/224791267-14a269b9-71e6-4f3a-88df-6f4e16b04627.png)
![2023-03-13_11-08-37](https://user-images.githubusercontent.com/1533929/224791285-d181e9fc-7685-4c30-9724-9fa8b3d2e433.png)

**Comment by hezzze** [comment]
I think I've got the same issue

![image](https://user-images.githubusercontent.com/2413682/224897804-26168372-352c-4401-927c-8e4cd50d8953.png)

![image](https://user-images.githubusercontent.com/2413682/224897839-293dddb8-ce76-453b-9623-591202caeadd.png)

![image](https://user-images.githubusercontent.com/2413682/224897924-7bc73578-bac0-4549-8a90-087de2255adb.png)

![image](https://user-images.githubusercontent.com/2413682/224897944-9c4035d8-c962-4db0-ae41-403099dc0466.png)

what's missing here xD

**Comment by hezzze** [comment]
even tried the image from the demo...

![image](https://user-images.githubusercontent.com/2413682/224898444-8254f277-8ce9-44e5-af70-9172936ac0a3.png)

![image](https://user-images.githubusercontent.com/2413682/224898483-4144a514-4454-4145-9e99-fa1398e22099.png)

![image](https://user-images.githubusercontent.com/2413682/224899249-992a9227-9c9f-476a-8b0e-252ee5b977e1.png)

![image](https://user-images.githubusercontent.com/2413682/224899304-98f28936-8145-428c-8908-73b57e9aaf56.png)

**Comment by ddzipp** [comment]
Me too, It seems that the  demo don't  understand the content before

**Comment by nazkhan-8451** [comment]
Maybe use the image name, "change the motorcycle on the image/3914e55f.jpg"

**Comment by ShengmingYin01** [comment]
Hi @hezzze and @emarutian 
For replacement and removement, you need to load the **ImageEditing**.
For Visual Question Answering, you need to load the **VisualQuestionAnswering**.
For changing the style, you need to load **InstructPix2Pix**.
Please make sure that you have loaded the visual foundation models you want to use.
Thanks~

**Comment by emarutian** [comment]
That's right.  That's was it.
