### ISSUE TITLE
ImportError: cannot import name 'CLIPSegProcessor' from 'transformers

### ISSUE THREAD

**Issue by aitechguy** [microsoft/visual-chatgpt#167]
Tried reinstalling the transformers using condo and pip multiple times, still getting this message...

<img width="1060" alt="2023-03-13_11-57-25" src="https://user-images.githubusercontent.com/127007197/224802945-300dfcbd-f087-4cc5-ba1e-ac68627354ab.png">

**Comment by Golevka2001** [comment]
Hey you didn't follow the steps in `README.md`.

**Comment by Wang-Xiaodong1899** [comment]
Hi @aitechguy , Did you follow the Quick Start steps in `README.md`? You can use the python3.8 and install the latest `transformers` via `pip install transformers`. 

Thanks~

**Comment by aitechguy** [comment]
closing. Tried to reinstall it and it worked this time.

**Comment by aitechguy** [comment]
Thank you for the response!
