### ISSUE TITLE
ConnectTimeoutError

### ISSUE THREAD

**Issue by Illusionist0** [microsoft/visual-chatgpt#168]
- 为什么会超时？需要挂相关代理或者其他的什么吗？我是在远程服务器上跑的

**Comment by Illusionist0** [comment]
![issue1](https://user-images.githubusercontent.com/45280235/224830616-315ce756-4f0f-4ed4-9083-348d178ff121.png)
![issue2](https://user-images.githubusercontent.com/45280235/224830625-e5eee13d-fc1f-459c-bd3f-c17a2e454aea.png)
![issue3](https://user-images.githubusercontent.com/45280235/224830630-c1278c4a-a953-4b53-90c8-86dcce54cb51.png)

**Comment by Illusionist0** [comment]
- 有人知道具体为什么吗？

**Comment by Golevka2001** [comment]
这里是在从 HuggingFace 下载预训练模型，你可以试试直接访问网站，看是不是没有挂代理的问题。实在不行就直接在网站手动下载，再导入到路径下。
