### ISSUE TITLE
Images are not displayed after gradio 3.21.0 release

### ISSUE THREAD

**Issue by rupeshs** [microsoft/visual-chatgpt#173]
I have created a quick fix for that PR : https://github.com/microsoft/visual-chatgpt/pull/172
![gradio-images-not-displyed-issue](https://user-images.githubusercontent.com/3255994/224882212-098bddfd-9ad2-4fe0-9437-d1a9d2c42f02.PNG)

**Comment by ddzipp** [comment]
the same, I have met this problem this morning. Have you ever solved this problem?

**Comment by rupeshs** [comment]
@ddzipp It is fixed, I have a PR for that now it is merged.
