### ISSUE TITLE
Can you provide a detailed description about the paras after "--load"

### ISSUE THREAD

**Issue by Golevka2001** [microsoft/visual-chatgpt#174]
I'm confused about the parameters, like `Text2Image_cuda:0`.

And I hope a more detailed description can be provided. Then users can enter proper paras to match their own GPUs with different memory.

**Comment by Wang-Xiaodong1899** [comment]
Hi @Golevka2001 , we just updated the details in `README.md`.
The parameter `--load` indicates which Visual Foundation Model to use and where it will be loaded to. The model and device are sperated by underline '_', the different models are seperated by comma ','. The available Visual Foundation Models can be found in the table. 
For example, if you want to load ImageCaptioning to cpu and Text2Image to cuda:0, use: `--load ImageCaptioning_cpu,Text2Image_cuda:0`

Thanks~

**Comment by Golevka2001** [comment]
> Hi @Golevka2001 , we just updated the details in `README.md`. The parameter `--load` indicates which Visual Foundation Model to use and where it will be loaded to. The model and device are sperated by underline '_', the different models are seperated by comma ','. The available Visual Foundation Models can be found in the table. For example, if you want to load ImageCaptioning to cpu and Text2Image to cuda:0, use: `--load ImageCaptioning_cpu,Text2Image_cuda:0`
> 
> Thanks~

Appreciate for your continent reply!
