### ISSUE TITLE
ValueError: "ConversationBufferMemory" object has no field "buffer"

### ISSUE THREAD

**Issue by dawarazhar11** [microsoft/visual-chatgpt#179]
self.agent.memory.buffer = cut_dialogue_history(self.agent.memory.buffer, keep_last_n_words=500)
  File "pydantic\main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "ConversationBufferMemory" object has no field "buffer"

**Comment by Wang-Xiaodong1899** [comment]
Hi @dawarazhar11 , it is a problem of `langchain` version, and you can fix it by `pip install langchain==0.0.101`. Thanks!

**Comment by dawarazhar11** [comment]
> Hi @dawarazhar11 , it is a problem of `langchain` version, and you can fix it by `pip install langchain==0.0.101`. Thanks!

Thanks. It worked.

**Comment by 1119736939** [comment]
thank you, it worked
