### ISSUE TITLE
Exception: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by czd2003** [microsoft/visual-chatgpt#181]
python visual_chatgpt.py --load "ImageCaptioning_cuda:0,Text2Image_cuda:0"
------------------------------------------------------------------------------------------------------------
Initializing VisualChatGPT, load_dict={'ImageCaptioning': 'cuda:0', 'Text2Image': 'cuda:0'}
Initializing ImageCaptioning to cuda:0
Initializing Text2Image to cuda:0
Fetching 15 files: 100%|██████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 74367.09it/s]
/home/mars/anaconda3/envs/visgpt/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/mars/git/visual-chatgpt/visual_chatgpt.py:889 in <module>                                  │
│                                                                                                  │
│   886 │   parser.add_argument('--load', type=str, default="ImageCaptioning_cuda:0,Text2Image_c   │
│   887 │   args = parser.parse_args()                                                             │
│   888 │   load_dict = {e.split('_')[0].strip(): e.split('_')[1].strip() for e in args.load.spl   │
│ ❱ 889 │   bot = ConversationBot(load_dict=load_dict)                                             │
│   890 │   with gr.Blocks(css="#chatbot .overflow-y-auto{height:500px}") as demo:                 │
│   891 │   │   chatbot = gr.Chatbot(elem_id="chatbot", label="Visual ChatGPT")                    │
│   892 │   │   state = gr.State([])                                                               │
│                                                                                                  │
│ /home/mars/git/visual-chatgpt/visual_chatgpt.py:828 in __init__                                  │
│                                                                                                  │
│   825 │   │                                                                                      │
│   826 │   │   self.models = dict()                                                               │
│   827 │   │   for class_name, device in load_dict.items():                                       │
│ ❱ 828 │   │   │   self.models[class_name] = globals()[class_name](device=device)                 │
│   829 │   │                                                                                      │
│   830 │   │   self.tools = []                                                                    │
│   831 │   │   for class_name, instance in self.models.items():                                   │
│                                                                                                  │
│ /home/mars/git/visual-chatgpt/visual_chatgpt.py:226 in __init__                                  │
│                                                                                                  │
│   223 │   │   print("Initializing Text2Image to %s" % device)                                    │
│   224 │   │   self.device = device                                                               │
│   225 │   │   self.torch_dtype = torch.float16 if 'cuda' in device else torch.float32            │
│ ❱ 226 │   │   self.pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v   │
│   227 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   torch_dtype=self.torch_dtype   │
│   228 │   │   self.pipe.to(device)                                                               │
│   229 │   │   self.a_prompt = 'best quality, extremely detailed'                                 │
│                                                                                                  │
│ /home/mars/anaconda3/envs/visgpt/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils. │
│ py:944 in from_pretrained                                                                        │
│                                                                                                  │
│    941 │   │   │   │                                                                             │
│    942 │   │   │   │   # check if the module is in a subdirectory                                │
│    943 │   │   │   │   if os.path.isdir(os.path.join(cached_folder, name)):                      │
│ ❱  944 │   │   │   │   │   loaded_sub_model = load_method(os.path.join(cached_folder, name), **  │
│    945 │   │   │   │   else:                                                                     │
│    946 │   │   │   │   │   # else load from the root directory                                   │
│    947 │   │   │   │   │   loaded_sub_model = load_method(cached_folder, **loading_kwargs)       │
│                                                                                                  │
│ /home/mars/anaconda3/envs/visgpt/lib/python3.8/site-packages/transformers/modeling_utils.py:2301 │
│ in from_pretrained                                                                               │
│                                                                                                  │
│   2298 │   │   if from_pt:                                                                       │
│   2299 │   │   │   if not is_sharded and state_dict is None:                                     │
│   2300 │   │   │   │   # Time to load the checkpoint                                             │
│ ❱ 2301 │   │   │   │   state_dict = load_state_dict(resolved_archive_file)                       │
│   2302 │   │   │                                                                                 │
│   2303 │   │   │   # set dtype to instantiate the model under:                                   │
│   2304 │   │   │   # 1. If torch_dtype is not None, we use that dtype                            │
│                                                                                                  │
│ /home/mars/anaconda3/envs/visgpt/lib/python3.8/site-packages/transformers/modeling_utils.py:402  │
│ in load_state_dict                                                                               │
│                                                                                                  │
│    399 │   """                                                                                   │
│    400 │   if checkpoint_file.endswith(".safetensors") and is_safetensors_available():           │
│    401 │   │   # Check format of the archive                                                     │
│ ❱  402 │   │   with safe_open(checkpoint_file, framework="pt") as f:                             │
│    403 │   │   │   metadata = f.metadata()                                                       │
│    404 │   │   if metadata.get("format") not in ["pt", "tf", "flax"]:                            │
│    405 │   │   │   raise OSError(                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
Exception: Error while deserializing header: HeaderTooLarge

--------------------------------------------------------------------------------------
GPU:A6000  
Pytorch 1.13.1+cu11.6

**Comment by yehx1** [comment]
Exception: Error while deserializing header: HeaderTooLarge
same error. Do you solve it?

**Comment by czd2003** [comment]
It may have been caused by an incomplete download of the model file. After re-downloading, the problem was resolved.

**Comment by Celeste-cj** [comment]
I read the raw code and found out that the problem is caused by trying to load file in safetensors format.
So you can try to pass an aux argument like 
`use_safetensors=False`

**Comment by llsdlkf** [comment]
> I read the raw code and found out that the problem is caused by trying to load file in safetensors format. So you can try to pass an aux argument like `use_safetensors=False`

can you give some details?

**Comment by llsdlkf** [comment]
be more specific

**Comment by llsdlkf** [comment]
recreating all vector stores
2024-01-24 02:39:24,022 - faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/bge-large-zh' from disk.
2024-01-24 02:39:24,320 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /bge-large-zh
2024-01-24 02:39:25,129 - embeddings_api.py[line:39] - ERROR: Error while deserializing header: HeaderTooLarge
AttributeError: 'NoneType' object has no attribute 'conjugate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Langchain-Chatchat-v0.2.8/init_database.py", line 108, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/Langchain-Chatchat-v0.2.8/server/knowledge_base/migrate.py", line 121, in folder2db
    kb.create_kb()
  File "/Langchain-Chatchat-v0.2.8/server/knowledge_base/kb_service/base.py", line 81, in create_kb
    self.do_create_kb()
  File "/Langchain-Chatchat-v0.2.8/server/knowledge_base/kb_service/faiss_kb_service.py", line 47, in do_create_kb
    self.load_vector_store()
  File "/Langchain-Chatchat-v0.2.8/server/knowledge_base/kb_service/faiss_kb_service.py", line 28, in load_vector_store
    return kb_faiss_pool.load_vector_store(kb_name=self.kb_name,
  File "/Langchain-Chatchat-v0.2.8/server/knowledge_base/kb_cache/faiss_cache.py", line 90, in load_vector_store
    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
  File "/Langchain-Chatchat-v0.2.8/server/knowledge_base/kb_cache/faiss_cache.py", line 48, in new_vector_store
    vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True)
  File "/root/miniconda3/envs/env_name/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 508, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/root/miniconda3/envs/env_name/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 913, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "/Langchain-Chatchat-v0.2.8/server/knowledge_base/kb_service/base.py", line 399, in embed_documents
    return normalize(embeddings).tolist()
  File "/Langchain-Chatchat-v0.2.8/server/knowledge_base/kb_service/base.py", line 38, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "<__array_function__ internals>", line 200, in norm
  File "/root/miniconda3/envs/env_name/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 2541, in norm
    s = (x.conj() * x).real
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by llsdlkf** [comment]
this is my error ,what's the trouble

**Comment by jessicaaashen** [comment]
seems we can solve this problem by redownloading
