### ISSUE TITLE
Program crash when generating image: Mac M1 Pro

### ISSUE THREAD

**Issue by nazkhan-8451** [microsoft/visual-chatgpt#187]
Action: Generate Image From User Input Text
100%|████████████████████████████████████████████████████████████████████████████████████| 50/50 [03:23<00:00,  4.06s/it]
[2]    91716 bus error  python visual_chatgpt.py --load ImageCaptioning_cpu,Text2Image_cpu
/Users/x/miniconda3/envs/visgpt/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by Omaraldarwish** [comment]
same here!

**Comment by nazkhan-8451** [comment]
yes

**Comment by wastu01** [comment]
same problem in M1

**Comment by wastu01** [comment]
https://github.com/pytorch/pytorch/issues/96610

**Comment by Xwixpacer** [comment]
https://trafficadbar.com/Maryannbustamante

**Comment by Xwixpacer** [comment]
https://trafficadbar.com/Maryannbustamante

**Comment by MvCraK** [comment]
python visual_chatgpt.py --load ImageCaptioning_cpu,ImageEditing_cpu,Text2Image_cpu

**Comment by MvCraK** [comment]
> python visual_chatgpt.py --load ImageCaptioning_cpu,ImageEditing_cpu,Text2Image_cpu

add ImageEditing

**Comment by wastu01** [comment]
ok got to try it

**Comment by nazkhan-8451** [comment]
> > python visual_chatgpt.py --load ImageCaptioning_cpu,ImageEditing_cpu,Text2Image_cpu
> 
> add ImageEditing

This doesn't solve the problem.

**Comment by nazkhan-8451** [comment]
I have followed this: https://github.com/microsoft/visual-chatgpt/issues/37. Made some change (requests, langchain library version to make it work). Doesn't solve the problem. I am closing this as I am done trying to make it work.

**Comment by taohaowei** [comment]
> > > python visual_chatgpt.py --load ImageCaptioning_cpu,ImageEditing_cpu,Text2Image_cpu
> > 
> > 
> > add ImageEditing
> 
> This doesn't solve the problem.

me too
