### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Rhoades1** [microsoft/visual-chatgpt#192]
Hello everyone, sorry for my ignorance on the subject, but I can't figure out how to download. Can anyone tell me what should I do?

**Comment by thibaultmol** [comment]
Literally a quick start on the readme of this repo....

**Comment by Rhoades1** [comment]
First of all thanks for your answer. I'm sorry but I'm not familiar with these things: what is "readme"? How do I do the "quick start"? What "repo" are you referring to?

**Comment by thibaultmol** [comment]
Oh God.. honestly ask chatgpt or bing chat "how to run visual chatgpt.

Also, if you don't know these things. I highly doubt you have the gpu to run this project anyway. So probably best to give up and use the online demo (when it's working again)

**Comment by chenfei-wu** [comment]
Hi @Rhoades1 

Use `git clone https://github.com/microsoft/visual-chatgpt.git` to download.
