### ISSUE TITLE
[Enhancement] Colab notebook with 10 tools

### ISSUE THREAD

**Issue by rupeshs** [microsoft/visual-chatgpt#194]
I have added and tested 10 tools in colab notebook(13GB VRAM - Single GPU).
The following tools are enabled by default:
- Text2Image
- ImageCaptioning
- CannyText2Image
- InstructPix2Pix
- VisualQuestionAnswering
- Image2Canny
- Image2Line
- Image2Pose
- Image2Depth
- Image2Seg
Please check the repo for colab link and details.
https://github.com/rupeshs/visual-chatgpt/tree/colab-xformers-support-2

**Comment by chenfei-wu** [comment]
Thanks @rupeshs, I have updated the Colab.

**Comment by rupeshs** [comment]
@chenfei-wu That is really cool.
