### ISSUE TITLE
Failed to connect to WebUI 

### ISSUE THREAD

**Issue by Fenfel** [microsoft/visual-chatgpt#195]
I open https://0.0.0.0:7868 in my browser as the console writes but nothing happens "Cannot connect to site." Maybe it has something to do with the line "vae\diffusion_pytorch_model.safetensors not found" but I do not even know where this folder is and what models can be used or where i can download diffusion_pytorch_model.safetensors
![image](https://user-images.githubusercontent.com/127771767/225108687-32f7bfa3-f0b6-4afd-ac5c-2f2108d79b6d.png)

**Comment by nathan927** [comment]
same situation

**Comment by Fenfel** [comment]
okay I fixed it by replacing in visual_chatgpt.py 0.0.0.0:7868 with 127.0.0.1:7860 like automatic1111 but now the following error Also in the beginning set OPENAI_API_KEY=**** without! {} otherwise the console gives an error about the wrong API key.

**Comment by Fenfel** [comment]
> same situation

1.Откройте visual_chatgpt.py
2.пролистайте до самой последней строчки demo.launch(server_name="0.0.0.0", server_port=7868)
3.замените её на demo.launch(server_name="127.0.0.1", server_port=7860)

**Comment by tam9life** [comment]
It opens with the following link
http://127.0.0.1:7868/
