### ISSUE TITLE
已经部署成功，也可以正常生产图片，但是无法根据进一步提示调整图片内容，是什么问题。

### ISSUE THREAD

**Issue by teanhow** [microsoft/visual-chatgpt#198]
<img width="534" alt="截屏2023-03-15 09 53 18" src="https://user-images.githubusercontent.com/76635628/225184265-9855e876-4eba-45bd-9559-e6cc1f6068ea.png">

我参考demo让它把猫改成狗。。结果他还是给了另外一张猫的图。

**Comment by Liweixin22** [comment]
我也是

**Comment by Liweixin22** [comment]
而且Hugginface的效果好过自己在colab部署的。

**Comment by chenfei-wu** [comment]
Hi @teanhow  and @Liweixin22 ,

如果需要替换功能，要载入ImageEditing_cuda:0

**Comment by teanhow** [comment]
> Hi @teanhow and @Liweixin22 ,
> 
> 如果需要替换功能，要载入ImageEditing_cuda:0

谢谢。

**Comment by Liweixin22** [comment]
谢谢🙏
