### ISSUE TITLE
Improving Readability: Separate Quick Start into Multiple Code Blocks in ReadMe

### ISSUE THREAD

**Issue by Arindam200** [microsoft/visual-chatgpt#200]
## The Quick Start part of the `ReadMe` is written in a single code block, which can make it hard to read and follow. 

![image](https://user-images.githubusercontent.com/109217591/225203818-eff3e214-a42f-4ba3-8c1f-5bd776e8d3a2.png)

## To improve readability, the code should be separated into multiple blocks with clear headings and concise instructions. This will make it easier for new users to get started with the codebase.

My Suggestion: 
![image](https://user-images.githubusercontent.com/109217591/225205650-6a7e99cf-fa5a-47b3-beb7-04a50b2b90d7.png)

**Comment by chenfei-wu** [comment]
Thanks, but we do not think it would be necessary to separate into multiple blocks with each block only contain one single line.

**Comment by Arindam200** [comment]
Thanks for the Feedback!
