### ISSUE TITLE
Models Descriptions

### ISSUE THREAD

**Issue by JihadAKl** [microsoft/visual-chatgpt#207]
Can you provide us with a description for the available models in the readme file?

**Comment by shengming-yin** [comment]
You can find the available models here https://github.com/microsoft/visual-chatgpt/blob/ed64e98130e80e3e51ecefdff994da93f822723d/README.md?plain=1#L94

Thanks~

**Comment by JihadAKl** [comment]
We need a description for each model what it is used for. Most of the models does not provide this by their name.
