### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by yananliusdu** [microsoft/visual-chatgpt#21]
thanks for your amazing project.

I am trying to test on my Ubuntu20.04 with a GPU of RTX 3080, it gives following errors,

`RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so 
the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
`

I had tried my times but it still remained unsolved, do you have any hints on this issue?

thanks
![Screenshot from 2023-03-09 19-03-30](https://user-images.githubusercontent.com/35995716/224128414-ac553dd6-8e45-4651-9d8c-cc794f515e69.png)

**Comment by b2zer** [comment]
There's two of the pretty much same answers that will solve your problem in the "closed" issues at this point; please check there.

**Comment by b2zer** [comment]
https://github.com/microsoft/visual-chatgpt/issues?q=is%3Aissue+is%3Aclosed :-)
