### ISSUE TITLE
Image Editing Problem in Mac M1

### ISSUE THREAD

**Issue by wastu01** [microsoft/visual-chatgpt#212]
when I asking remove something. it running about 8~12 minute and get error

 Error 1 leaked semaphore objects
opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by wastu01** [comment]
asking for chatGPT : 我理解了你的問題。由於 Visual-ChatGPT 能夠根據語言提示自動生成圖像，因此需要使用圖像編輯命令來處理圖像。但是，目前在 M1 Mac 上運行的問題是，該命令可能會與 Rosetta 2 不兼容，導致無法執行。

**Comment by wastu01** [comment]
but asking for image info is ok. just image editing problem

[Microsoft Visual ChatGPT Image Analyze using Chinese Input](https://youtu.be/2Uow3cTOWPg)

**Comment by MvCraK** [comment]
添加个ImageEditing，比如python visual_chatgpt.py --load ImageCaptioning_cpu,ImageEditing_cpu,Text2Image_cpu

**Comment by wastu01** [comment]
p.s type python3 when using Mac

**Comment by wastu01** [comment]
> 添加个ImageEditing，比如python visual_chatgpt.py --load ImageCaptioning_cpu,ImageEditing_cpu,Text2Image_cpu

ok. I fixed it already.
