### ISSUE TITLE
Can not generate the same results like the paper showed.

### ISSUE THREAD

**Issue by zhx999** [microsoft/visual-chatgpt#216]
<img width="1785" alt="Capture1" src="https://user-images.githubusercontent.com/88083619/225646904-fe833a4e-778d-4763-8b93-fbf8701f78a6.PNG">
<img width="1778" alt="Capture2" src="https://user-images.githubusercontent.com/88083619/225647247-e2cbfbea-ff8e-4729-a964-2009f9cc7aa0.PNG">

I am running the newest version of this visual-chatgpt, currently I can not generate decent results like the paper showed. Any ideas? I am using Windows system

**Comment by Wang-Xiaodong1899** [comment]
Hi @zhx999, What is the command that you used to launch the Visual ChatGPT? I was wondering if you loaded the ImageEditing and InstructPix2Pix. The parameter `--load` you used should include these two models. BTW, can you share the image you used? So I can debug it to figure out what went wrong?

**Comment by Wang-Xiaodong1899** [comment]
![image](https://user-images.githubusercontent.com/44627574/225805617-9618551c-9b00-40d4-8f80-c42c23d31b3c.png)
Hello, I tested the example again and it worked as expected. Note: `--load` should include ImageCaptioning, ImageEditing, and InstructPix2Pix.

**Comment by zhx999** [comment]
Hi Xiaodong, you are right. Previously I didn't include the "InstructPix2Pix" to the command. With the command you mentioned, I successfully generated a similar picture.

I will explore more about your excellent work.

All the best  
<img width="1129" alt="Screenshot 2023-03-17 at 4 10 05 PM" src="https://user-images.githubusercontent.com/88083619/225914532-95bd183a-4fdf-458e-aa05-94e79d4a0c8d.png">
