### ISSUE TITLE
can not edit image in Mac M1 

### ISSUE THREAD

**Issue by harrison001** [microsoft/visual-chatgpt#221]
I simply type the following command and it works fine and much faster than using cpu.
 python visual_chatgpt.py --load ImageCaptioning_mps,Text2Image_mps

But I recognized that the image editing can not work. I noticed that it is because the method was never called other than any error in code.

So  can anyone do the image edit in other platform?

**Comment by harrison001** [comment]
update:
I just run it with the the followings. Everything works fine now.
python visual_chatgpt.py --load "ImageCaptioning_mps:0,ImageEditing_mps:0,
    Text2Image_mps:1,Image2Canny_cpu,CannyText2Image_mps:1,
    Image2Depth_cpu,DepthText2Image_mps:1,VisualQuestionAnswering_mps:2,
    InstructPix2Pix_mps:2,Image2Scribble_cpu,ScribbleText2Image_mps:2,
    Image2Seg_cpu,SegText2Image_mps:2,Image2Pose_cpu,PoseText2Image_mps:2,
    Image2Hed_cpu,HedText2Image_mps:3,Image2Normal_cpu,
    NormalText2Image_mps:3,Image2Line_cpu,LineText2Image_mps:3"

**Comment by shengming-yin** [comment]
Thanks @harrison001 ! You need to load ImageEditing model to enable the image edit.

**Comment by harrison001** [comment]
@shengming-yin yes. You are right. Much faster now, enjoying...
