### ISSUE TITLE
The webpage at http://0.0.0.0:7868/ might be temporarily down or it may have moved permanently to a new web address.

### ISSUE THREAD

**Issue by Li-Yidong** [microsoft/visual-chatgpt#224]
非常感谢您的分享！
我在运行了.py文件之后, 在Terminal中正常出现了:
`Running on local URL:  http://0.0.0.0:7868`

但是无法访问这个本地网页，是因为我的网络设置问题吗？
期待您的回复！

**Comment by Li-Yidong** [comment]
我不在中国大陆，所以没有开代理。
现在在考虑是不是因为使用的是公司的网络的问题？（对于网络知识一窍不通）

**Comment by Li-Yidong** [comment]
> 关掉代理！ 服务运行开始时开启代理，等服务运行后，再关闭

感谢您的回复！
我不在中国大陆，所以没有开代理。
现在在考虑是不是因为使用的是公司的网络的问题？（对于网络知识一窍不通）

**Comment by malaTomato** [comment]
应该不是，尝试使用 http://localhost:7868
