### ISSUE TITLE
ImportError: cannot import name 'StableDiffusionControlNetPipeline' from 'diffusers'

### ISSUE THREAD

**Issue by BarryTheShen** [microsoft/visual-chatgpt#226]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\Barry\visual_chatgpt\visual-chatgpt\visual_chatgpt.py:18 in <module>                          │
│                                                                                                  │
│    15                                                                                            │
│    16 from diffusers import StableDiffusionPipeline, StableDiffusionInpaintPipeline, StableDif   │
│    17 from diffusers import EulerAncestralDiscreteScheduler                                      │
│ ❱  18 from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistep   │
│    19 from controlnet_aux import OpenposeDetector, MLSDdetector, HEDdetector                     │
│    20                                                                                            │
│    21 from langchain.agents.initialize import initialize_agent                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'StableDiffusionControlNetPipeline' from 'diffusers'

**Comment by Wang-Xiaodong1899** [comment]
Hi @BarryTheShen, the latest version of `diffusers` 0.14.0 works normally. Can you try to fix it via `pip install diffusers==0.14.0`? 

Thanks~

**Comment by BarryTheShen** [comment]
Ok Thank you

**Comment by Nughu** [comment]
> Hi @BarryTheShen, the latest version of `diffusers` 0.14.0 works normally. Can you try to fix it via `pip install diffusers==0.14.0`?
> 
> Thanks~

after doing this I get another error:

`Traceback (most recent call last):
  File "X:\AI\Stable-Diffusion-ONNX-FP16\OnnxDiffusersUI\onnxUI.py", line 1288, in <module>
    image_t2 = gr.Image(
               ^^^^^^^^^
  File "X:\AI\Stable-Diffusion-ONNX-FP16\sd_env\Lib\site-packages\gradio\component_meta.py", line 157, in wrapper
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: Image.__init__() got an unexpected keyword argument 'source'`
