### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out

### ISSUE THREAD

**Issue by tianyang1027** [microsoft/visual-chatgpt#229]
![image](https://user-images.githubusercontent.com/7963894/225802316-16959374-cbba-447b-b534-c09773e43d72.png)

**Comment by zkpanhao** [comment]
Set http_proxy or https_proxy first

**Comment by shaowin16** [comment]
> Set http_proxy or https_proxy first

How to set up an HTTP proxy? Do I need to use VPN to bypass the firewall?

**Comment by shaowin16** [comment]
已收到，谢谢！

**Comment by Zhangwq76** [comment]
请问您具体是如何解决的，我也遇到了相同的问题TAT
