### ISSUE TITLE
Stuck on ldm. Any ideas on how to fix it? (Windows)

### ISSUE THREAD

**Issue by itsWinwin** [microsoft/visual-chatgpt#23]
#UPDATED! I'm stuck on this:

SUCCESS: Specified value was saved.

(visgpt) C:\Users\itswi\visual-chatgpt>mkdir image

(visgpt) C:\Users\itswi\visual-chatgpt>python visual_chatgpt.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\itswi\visual-chatgpt\visual_chatgpt.py:26 in <module>                                   │
│                                                                                                  │
│    23 import einops                                                                              │
│    24 from pytorch_lightning import seed_everything                                              │
│    25 import random                                                                              │
│ ❱  26 from ldm.util import instantiate_from_config                                               │
│    27 from ControlNet.cldm.model import create_model, load_state_dict                            │
│    28 from ControlNet.cldm.ddim_hacked import DDIMSampler                                        │
│    29 from ControlNet.annotator.canny import CannyDetector                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'ldm'

(visgpt) C:\Users\itswi\visual-chatgpt>pip install ldm
Collecting ldm
  Downloading ldm-0.1.3.tar.gz (6.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ldm
  Building wheel for ldm (setup.py) ... done
  Created wheel for ldm: filename=ldm-0.1.3-py3-none-any.whl size=6228 sha256=c873edd9da3840ccadbd5c39e37664b890c9941c7ad8f1d7bbba47a07921f1f3
  Stored in directory: c:\users\itswi\appdata\local\pip\cache\wheels\c2\f5\78\5d08a3bc3b3a8ade07c0089eacb49f2a2e11e04a5d7e7daad1
Successfully built ldm
Installing collected packages: ldm
Successfully installed ldm-0.1.3

(visgpt) C:\Users\itswi\visual-chatgpt>python visual_chatgpt.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\itswi\visual-chatgpt\visual_chatgpt.py:26 in <module>                                   │
│                                                                                                  │
│    23 import einops                                                                              │
│    24 from pytorch_lightning import seed_everything                                              │
│    25 import random                                                                              │
│ ❱  26 from ldm.util import instantiate_from_config                                               │
│    27 from ControlNet.cldm.model import create_model, load_state_dict                            │
│    28 from ControlNet.cldm.ddim_hacked import DDIMSampler                                        │
│    29 from ControlNet.annotator.canny import CannyDetector                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  C:\Users\itswi\anaconda3\envs\visgpt\lib\site-packages\ldm.py:20                                │
│         print self.face_rec_model_path                                                           │
│               ▲                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

(visgpt) C:\Users\itswi\visual-chatgpt>

**Comment by itsWinwin** [comment]
Here's where I'm not proper stuck:

(base) C:\Users\myuser\visual-chatgpt>python visual_chatgpt.py
Traceback (most recent call last):
  File "C:\Users\myuser\visual-chatgpt\visual_chatgpt.py", line 22, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

(base) C:\Users\myuser\visual-chatgpt>pip install cv2
ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2

**Comment by itsWinwin** [comment]
seems like something went wrong when I installed requirement.txt .
Trying again now.

**Comment by itsWinwin** [comment]
Tried reinstalling, and now I'm stuck on this:


SUCCESS: Specified value was saved.

(visgpt) C:\Users\itswi\visual-chatgpt>mkdir image

(visgpt) C:\Users\itswi\visual-chatgpt>python visual_chatgpt.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\itswi\visual-chatgpt\visual_chatgpt.py:26 in <module>                                   │
│                                                                                                  │
│    23 import einops                                                                              │
│    24 from pytorch_lightning import seed_everything                                              │
│    25 import random                                                                              │
│ ❱  26 from ldm.util import instantiate_from_config                                               │
│    27 from ControlNet.cldm.model import create_model, load_state_dict                            │
│    28 from ControlNet.cldm.ddim_hacked import DDIMSampler                                        │
│    29 from ControlNet.annotator.canny import CannyDetector                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'ldm'

(visgpt) C:\Users\itswi\visual-chatgpt>pip install ldm
Collecting ldm
  Downloading ldm-0.1.3.tar.gz (6.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ldm
  Building wheel for ldm (setup.py) ... done
  Created wheel for ldm: filename=ldm-0.1.3-py3-none-any.whl size=6228 sha256=c873edd9da3840ccadbd5c39e37664b890c9941c7ad8f1d7bbba47a07921f1f3
  Stored in directory: c:\users\itswi\appdata\local\pip\cache\wheels\c2\f5\78\5d08a3bc3b3a8ade07c0089eacb49f2a2e11e04a5d7e7daad1
Successfully built ldm
Installing collected packages: ldm
Successfully installed ldm-0.1.3

(visgpt) C:\Users\itswi\visual-chatgpt>python visual_chatgpt.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\itswi\visual-chatgpt\visual_chatgpt.py:26 in <module>                                   │
│                                                                                                  │
│    23 import einops                                                                              │
│    24 from pytorch_lightning import seed_everything                                              │
│    25 import random                                                                              │
│ ❱  26 from ldm.util import instantiate_from_config                                               │
│    27 from ControlNet.cldm.model import create_model, load_state_dict                            │
│    28 from ControlNet.cldm.ddim_hacked import DDIMSampler                                        │
│    29 from ControlNet.annotator.canny import CannyDetector                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  C:\Users\itswi\anaconda3\envs\visgpt\lib\site-packages\ldm.py:20                                │
│         print self.face_rec_model_path                                                           │
│               ▲                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

(visgpt) C:\Users\itswi\visual-chatgpt>

**Comment by b2zer** [comment]
The "module" is actually a folder (subfolder). That's the thing I have been confused about with Python for a year easily. :-)
For example, you could git clone https://github.com/lllyasviel/ControlNet.git and then copy the /ldm /cldm and /annotators you found in that folder you just git cloned, and move them to ./visual-chatgpt.

For example, this fancy from ldm.util import instantiate_from_config pretty much means it is looking for a folder called ldm in
C:\Users\itswi\visual-chatgpt, meaning it wants C:\Users\itswi\visual-chatgpt\ldm and then it wants a util.py file to be there so it can load instantiate_from_config from it: C:\Users\itswi\visual-chatgpt\ldm\util.py is what it wants to be there.

Also, just put an empty text file in the visual-chatgpt folder and rename it to:
__init__.py 

Trust me. ;-)
(It actually tells Python that this is something it can ingest, and often contains much more details on what specifically can and should be ingested from subfolders. You can look at more __init__.py that will be abundant in your [system-python-dir] to see how that works.)

**Comment by b2zer** [comment]
NARF. Git renamed that. There is two underscores before init.py, and then two underscores after the init. Let's try this:
--init--.py 
If you can see two --, then just replace that with two of _underscores.

**Comment by semmyk-research** [comment]
[quick one]
Seems issues #20 and #23 are related.
