### ISSUE TITLE
Failed to trigger correct  segmentation model

### ISSUE THREAD

**Issue by ddzipp** [microsoft/visual-chatgpt#238]
I want to use the semantic segmentation model from this project. That‘s what I do to interact:
![68ecfecf2a4c77ea4003adc85d3b078](https://user-images.githubusercontent.com/87225910/225907654-7d7220b4-cf4d-4a00-a39b-e489f07615df.png)
It is a strange result and I try again:
![e8a7274ba9570dbf46fa4080f714b26](https://user-images.githubusercontent.com/87225910/225908086-2f39491f-aff5-4f61-b9ec-a910f07c393c.png)
And for this time, I suspect that ChatGPT does not trigger the semantic segmentation model correctly.
I carefully read the related codes in visual_chatgpt.py and I am sure that the commands I entered should not cause ambiguity.
And I find out that the console give a correct action but choose a wrong model( image2pose????)
![355aa22b6419de861ac5859b37d0079](https://user-images.githubusercontent.com/87225910/225909761-afa1b58a-2ba9-4295-a1f9-0dfed17c3147.png)

**Comment by Wang-Xiaodong1899** [comment]
hi @ddzipp , can you provide these two images to me? I want to reproduce it to find out what went wrong. Thanks~

**Comment by ddzipp** [comment]
Sorry, the demo was running on Google's Colab and I didn't save the images. But I still came across similar examples after re-running the demo.
![demo1](https://user-images.githubusercontent.com/87225910/226085530-26c4411a-7a6b-4be2-a180-bbc198611e2d.png)
![demo2](https://user-images.githubusercontent.com/87225910/226085536-ae1df1a2-855f-469d-86e3-47883cc74397.png)
![demo3](https://user-images.githubusercontent.com/87225910/226085562-51b2763e-eec5-4175-a272-99acefcba016.png)
![demo4](https://user-images.githubusercontent.com/87225910/226085566-493f914e-b02e-4478-bb4a-af398d7151f9.png)
It seems that the segmentation model was triggered but it do not work very well.
What I find strange is that when the console shows Action as segmentation, the model chosen is Image2pose
![image](https://user-images.githubusercontent.com/87225910/226085874-39e491fe-27aa-406a-89d0-09316734ec9c.png)

**Comment by Wang-Xiaodong1899** [comment]
hi @ddzipp, this is a typo that the processed function outputs should be modified to the correct `Image2Seg`, and it actually triggered the right Image2Seg model. Thanks very much! We will fix it.

**Comment by ddzipp** [comment]
> 

Thank you for reply. I am a junior student who is interested in the direction of semantic segmentation. However, I found that Visual ChatGPT has poor semantic segmentation results for some specific scenarios. I hope I can explore further and make some small efforts. Thanks again for your reply and your job!
