### ISSUE TITLE
Did not find openai_api_key

### ISSUE THREAD

**Issue by ShaBaoFa** [microsoft/visual-chatgpt#239]
i have set OPENAI_API_KEY=sk-**
but 
ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)

**Comment by wastu01** [comment]
I fixed that by adding 
# os.environ["OPENAI_API_KEY"] = "key" in Mac M1 environment

**Comment by ShaBaoFa** [comment]
> I fixed that by adding `os.environ["OPENAI_API_KEY"] = "key"` n Mac M1 environment

got it!thank you!

**Comment by wastu01** [comment]
btw this way is according to other issue content.

**Comment by wastu01** [comment]
https://github.com/microsoft/visual-chatgpt/issues/152
