### ISSUE TITLE
Unable to run Visual ChatGPT 4 on Mac : SSLError : SSLCertVerificationError(

### ISSUE THREAD

**Issue by Ostap26** [microsoft/visual-chatgpt#246]
The following error occurs while executing "python visual_chatgpt.py --load ImageCaptioning_cpu,Text2Image_cpu" command on Mac :

**SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: 
/Salesforce/blip-image-captioning-base/resolve/main/preprocessor_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] 
certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))**

**Comment by wastu01** [comment]
which version/system on your mac 
can you add more detail ?
I am using Mac M1 Ventura 13.2

**Comment by Ostap26** [comment]
I am using : 13.2.1 (22D68) Mac M1 .

**Comment by psaren** [comment]
I have the same problem on  Mac M1 Monterey 12.5.1

**Comment by vincent0314** [comment]
I have the same problem on mac big sur 11.1 , intel chip

**Comment by Ostap26** [comment]
I found a workaround for this problem.
add the following line to the visual_chatgpt.py , after imports :
os.environ['CURL_CA_BUNDLE'] = ''

this command disables cert validation, which is not good, but at least it solves the problem.

**Comment by Ostap26** [comment]
> @Ostap26 Where should i add `os.environ['CURL_CA_BUNDLE'] = ''`, can you be more clear?

yes, I wrote exactly in my answer where to put it, please read it again.
