### ISSUE TITLE
error in torchtext when excuse <python visual-chatgpt.py> 

### ISSUE THREAD

**Issue by K-tang-mkv** [microsoft/visual-chatgpt#25]
I run it on googlecolab, got python=3.9 and pip=23.0.1, when I run `python visual-chatgpt.py`, I got error like this below. It might be environmental pjromblen.
`OSError: /usr/local/lib/python3.9/dist-packages/torchtext/lib/libtorchtext.so: 
undefined symbol: 
_ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTy
peEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE`

**Comment by CODINNLG** [comment]
Hi, it seems that the CUDA version of googlecolab mismatches with ours.
For more solution, [https://github.com/NVIDIA/NeMo/issues/3176](https://github.com/NVIDIA/NeMo/issues/3176) may help.

**Comment by rupeshs** [comment]
@K-tang-mkv Yes I tried to implement colab version but got `OSError: /usr/local/lib/python3.9/dist-packages/torchtext/lib/libtorchtext.so` .

**Comment by K-tang-mkv** [comment]
> 

I solve this problem. The error happened because your torch and torchtext are not compatible, so try this `pip install torch==1.9 torchtext=0.10 torchvision==0.10 torchaudio==0.9` and then it will be fine

**Comment by bro28** [comment]
The same done pip install torch==1.9 torchtext=0.10 torchvision==0.10 torchaudio==0.9
