### ISSUE TITLE
OSError: [Errno 22] Invalid argument:

### ISSUE THREAD

**Issue by yangjinning** [microsoft/visual-chatgpt#253]
Always shows the error：

OSError: [Errno 22] Invalid argument: 'C:\\Users\\yangjinning/.cache\\huggingface\\hub\\models--Salesforce--blip-image-captioning-base\\snapshots\\9f3084c0600e544506a2d414647492a036fb1aa0\\pytorch_model.bin'

pytorch_model.bin was successfully downloaded. 
System: Windows

**Comment by keenmouse** [comment]
Windows Defender is quarantining pytorch_model.bin as soon as it's downloaded because it thinks it contains a virus. It's being discussed [here](https://github.com/invoke-ai/InvokeAI/issues/2989) and people are trying to determine for certain that the detection is a false positive.

**Comment by yangjinning** [comment]
Solved. Thanks a lot.
