### ISSUE TITLE
How make the visual-chatgpt port to use proxy?

### ISSUE THREAD

**Issue by 5huanghuai** [microsoft/visual-chatgpt#258]
i'm using v2raya , so i thinking the v2raya is to make the data touch internet through the someone port . But the visual-chatgpt is using another port to interact with user. I don't know how to make the visual-chatgpu using the port of v2raya.

**Comment by Golevka2001** [comment]
Global proxy mode.

**Comment by 5huanghuai** [comment]
Thank you very much
