### ISSUE TITLE
Undefined Symbol When Running .py file

### ISSUE THREAD

**Issue by harriswr** [microsoft/visual-chatgpt#29]
Hello,

I received the following error. I followed the "pip install -r requirement.txt" and "bash download.sh" set up from the main page.

/home/harriswr/codes/visual_gpt/visual-chatgpt-main/visual_chatgpt.py:22 in <module>             │
│                                                                                                  │
│    19 import numpy as np                                                                         │
│    20 from omegaconf import OmegaConf                                                            │
│    21 from transformers import pipeline, BlipProcessor, BlipForConditionalGeneration, BlipForQ   │
│ ❱  22 import cv2                                                                                 │
│    23 import einops                                                                              │
│    24 from pytorch_lightning import seed_everything                                              │
│    25 import random                                                                              │
│                                                                                                  │
│ /home/harriswr/codes/anaconda3/envs/visgpt/lib/python3.8/site-packages/cv2/__init__.py:5 in      │
│ <module>                                                                                         │
│                                                                                                  │
│    2 import os                                                                                   │
│    3 import sys                                                                                  │
│    4                                                                                             │
│ ❱  5 from .cv2 import *                                                                          │
│    6 from .data import *                                                                         │
│    7                                                                                             │
│    8 # wildcard import above does not import "private" variables like __version__                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

Any idea how to fix this?

**Comment by wearenocomputer** [comment]
This seemed to have solved it:

pip install opencv-python==4.5.1.48

I am running
Ubuntu  20.04.5 LTS

**Comment by harriswr** [comment]
That worked! Thank you!
