### ISSUE TITLE
basicsr下载失败

### ISSUE THREAD

**Issue by Francis-cell** [microsoft/visual-chatgpt#297]
![image](https://user-images.githubusercontent.com/63135995/228436424-2d54f302-1eb9-4e02-ae41-d3c095619190.png)
已经尝试过的方法：
1、更换Python版本（现在是3.9，更换到3.8版本尝试过）；
2、直接下载basicsr.tar.gaz使用pip install安装；
3、直接指定basicsr版本的方式；
4、逐个安装requirements.txt中的第三方库的方式；
都没有成功，有没有哪位大佬知道其他可能的原因以及对应的解决方案呢？感谢

**Comment by qs-lll** [comment]
pip install https://files.pythonhosted.org/packages/86/41/00a6b000f222f0fa4c6d9e1d6dcc9811a374cabb8abb9d408b77de39648c/basicsr-1.4.2.tar.gz

**Comment by Francis-cell** [comment]
> pip install https://files.pythonhosted.org/packages/86/41/00a6b000f222f0fa4c6d9e1d6dcc9811a374cabb8abb9d408b77de39648c/basicsr-1.4.2.tar.gz

刚刚尝试了一下，还是上面截图中的报错

**Comment by Francis-cell** [comment]
![Uploading image.png…]()
仔细阅读了一下报错，发现需要安装cpython，使用pip install cpython 之后问题解决了

**Comment by ram16g** [comment]
我也遇到了这个问题，使用 pip install cpython 并没有解决为问题

**Comment by Francis-cell** [comment]
> 我也遇到了这个问题，使用 pip install cpython 并没有解决问题
在下载失败的下面，查看错误信息，最前面有一个[error]XXX...，里面有你安装失败的那个包的相关信息，当时我这里错误是因为cpython包安装失败的，所以单独安装解决了问题

**Comment by ram16g** [comment]
> > 我也遇到了这个问题，使用 pip install cpython 并没有解决问题
> > 在下载失败的下面，查看错误信息，最前面有一个[error]XXX...，里面有你安装失败的那个包的相关信息，当时我这里错误是因为cpython包安装失败的，所以单独安装解决了问题

什么都没有做，莫名其妙就好了，编程靠的是运气  : )

**Comment by k23223** [comment]
> 



> 我也遇到了这个问题，使用 pip install cpython 并没有解决问题

是pip install cython不是pip install cpython

**Comment by huangyansen** [comment]
安装tb-nightly 可以解决我的问题

**Comment by luosiwu** [comment]
下载basicsr-1.4.2.tar.gz解压后，直接放在site-packages下，重命名为basicsr

**Comment by Prometheus-first** [comment]
pip install -i https://mirrors.aliyun.com/[pypi](https://so.csdn.net/so/search?q=pypi&spm=1001.2101.3001.7020)/simple tb-nightly
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple basicsr==1.4.2

**Comment by Dowgen** [comment]
我是跑deforum找了一个多小时没找到问题，最终靠楼上的哥们解决了。感谢
pip install tb-nightly -i https://mirrors.aliyun.com/pypi/simple
pip install basicsr==1.4.2

**Comment by bingsanyu** [comment]
我尝试了以上所有方法还是报错，最后`pip install basicsr --use-pep517`解决。

**Comment by yu1anan** [comment]
太强了，cython和cpython真的好容易看错

**Comment by huayuliu114514** [comment]
其实只要仔细看看报错的原因大概也能猜到还有什么东西没装，比如我就是没装tb-nightly，他给我报错ERROR: Could not find a version that satisfies the requirement tb-nightly (from basicsr) (from versions: none)ERROR: No matching distribution found for tb-nightly，装好以后就没问题了
