### ISSUE TITLE
OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by powderblock** [microsoft/visual-chatgpt#31]
Getting an error when trying to run `python visual_chatgpt.py` I have an RTX 3080 with 10GB GPU memory but I am getting the following error: `OutOfMemoryError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 10.00 GiB total capacity; 9.20 GiB already
allocated; 0 bytes free; 9.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
![image](https://user-images.githubusercontent.com/1458607/224241900-f06688a0-7ebc-4641-93d1-774b55b4e29e.png)

Any tips?

**Comment by powderblock** [comment]
I tried cutting down on the self.tools in an effort to save GPU memory but no luck.

Even with the self.tools look so slim:

```
class ConversationBot:
    def __init__(self):
        print("Initializing VisualChatGPT")
        self.llm = OpenAI(temperature=0)
        self.edit = ImageEditing(device="cuda:0")
        self.t2i = T2I(device="cuda:0")
        self.BLIPVQA = BLIPVQA(device="cuda:0")
        self.pix2pix = Pix2Pix(device="cuda:0")
        self.memory = ConversationBufferMemory(memory_key="chat_history", output_key='output')
        self.tools = [
            Tool(name="Generate Image From User Input Text", func=self.t2i.inference,
                 description="useful when you want to generate an image from a user input text and save it to a file. like: generate an image of an object or something, or generate an image that includes some objects. "
                             "The input to this tool should be a string, representing the text used to generate image. "),
            Tool(name="Remove Something From The Photo", func=self.edit.remove_part_of_image,
                 description="useful when you want to remove and object or something from the photo from its description or location. "
                             "The input to this tool should be a comma seperated string of two, representing the image_path and the object need to be removed. "),
            Tool(name="Replace Something From The Photo", func=self.edit.replace_part_of_image,
                 description="useful when you want to replace an object from the object description or location with another object from its description. "
                             "The input to this tool should be a comma seperated string of three, representing the image_path, the object to be replaced, the object to be replaced with "),

            Tool(name="Instruct Image Using Text", func=self.pix2pix.inference,
                 description="useful when you want to the style of the image to be like the text. like: make it look like a painting. or make it like a robot. "
                             "The input to this tool should be a comma seperated string of two, representing the image_path and the text. "),
            Tool(name="Answer Question About The Image", func=self.BLIPVQA.get_answer_from_question_and_image,
                 description="useful when you need an answer for a question based on an image. like: what is the background color of the last image, how many cats in this figure, what is in this figure. "
                             "The input to this tool should be a comma seperated string of two, representing the image_path and the question")]
```

Got the same error! You guys got super computers or what! Haha

**Comment by powderblock** [comment]
![image](https://user-images.githubusercontent.com/1458607/224245236-24731740-e9af-4db6-a5e3-f4ca2e279b42.png)
Found this table ... Seems promising.

**Comment by powderblock** [comment]
Fixed by cutting down the models to only 2 models (T2I and Pix2Pix where the total MB is less than 10 GB aka my GPU memory)

**Comment by tristanhanks** [comment]
Had the same issue, I also have a 10GB card and this is exactly what I needed to do.  I had to spend hours making this work on Windows, it's a shame we've had to reduce this to such little functionality.

**Comment by videscar** [comment]
Maybe it is a quite stupid question but... How did you cut down to the models you want? Which part of the code needs to be modified?

**Comment by tiiime** [comment]
> Maybe it is a quite stupid question but... How did you cut down to the models you want? Which part of the code needs to be modified?

Comment out some elements in self.tools array.

https://github.com/K-tang-mkv/visual-chatgpt-googlecolab/blob/main/visual_chatgpt.py#L826

**Comment by videscar** [comment]
> > Maybe it is a quite stupid question but... How did you cut down to the models you want? Which part of the code needs to be modified?
> 
> Comment out some field in `self` and elements in `self.tools` array.
> 
> https://github.com/K-tang-mkv/visual-chatgpt-googlecolab/blob/main/visual_chatgpt.py#L804

Perfect! Thanks!
