### ISSUE TITLE
Error installing requirements.txt

### ISSUE THREAD

**Issue by enriquemorenotent** [microsoft/visual-chatgpt#33]
![image](https://user-images.githubusercontent.com/368842/224253927-e09b4654-6514-4ad8-a84a-ca4db0e1e788.png)

Why is this problem popping up? I followed all the previous steps in the instructions

**Comment by andzejsp** [comment]
are you sure you are working in the conda environment? because it sounds like you are installing deps on the machine not the environment?

**Comment by enriquemorenotent** [comment]
Yes, I was following all the steps in order

**Comment by enriquemorenotent** [comment]
I am not sure if relevant but... if I try to install the requirements.txt 2 times in a row... the second time I get no errors

![image](https://user-images.githubusercontent.com/368842/224367904-5c625d01-cd8b-4527-b103-a40a9e5d5fd6.png)

**Comment by K-tang-mkv** [comment]
@enriquemorenotent the first time you got error because some packages they are incompatible and conflicts, create a new virtual environment and using python3.8 to install everything
