### ISSUE TITLE
No module named 'groundingdino'

### ISSUE THREAD

**Issue by fabien219200** [microsoft/visual-chatgpt#356]
After all the steps provided in the readme, I have this error when attempting to use the recommended cpu version
![image](https://user-images.githubusercontent.com/39243216/232429874-d5897c7d-ba4b-4ab0-8a2e-c71231ba4456.png)

Does anyone have the same problem ?

I also got this problem when I tried running it from Google Colab

**Comment by Wang-Xiaodong1899** [comment]
Hi @fabien219200, we import the `GroundingDINO` and `SAM` modules by default, so, you should install these modules by this command:
`pip install  git+https://github.com/IDEA-Research/GroundingDINO.git`
`pip install  git+https://github.com/facebookresearch/segment-anything.git`
After that, you can run" `python visual_chatgpt.py --load "Text2Box_cuda:0,Segmenting_cuda:0,
    Inpainting_cuda:0,ImageCaptioning_cuda:0`
Then, enjoy using the **detection** or **segmentation-anything** only by uploading an image and sending a sentence like "Find the cat in this image".
Thanks for your comment, we are updating the Colab code.

**Comment by fabien219200** [comment]
Great, works like a charm
Thank you :)
