### ISSUE TITLE
M1 Mac users: Working `requirements.txt` set of dependencies and porting this code to M1 Mac, Python 3.9 (and update to Langchain 0.0.106)

### ISSUE THREAD

**Issue by sw-yx** [microsoft/visual-chatgpt#37]
> Edit: all the explorations have been recapped below: https://github.com/microsoft/visual-chatgpt/issues/37#issuecomment-1465469089

---

spent an hour fumbling around in dependency hell (e.g. #19) before giving up, deleting all deps and reinstalling latest versions of everything from scratch so here's my requirements dump

(new one thanks to @focus000 below)
```
accelerate==0.17.0
addict==2.4.0
albumentations==1.3.0
basicsr==1.4.2
diffusers==0.14.0
einops==0.3.2
gradio==3.20.1
imageio==2.26.0
imageio-ffmpeg==0.4.8
invisible-watermark==0.1.5
kornia==0.6.10
langchain==0.0.106
numpy==1.23.4
omegaconf==2.3.0
openai==0.24.0
opencv-contrib-python==4.7.0.72
open-clip-torch==2.16.0
prettytable==3.6.0
pytorch-lightning==1.6.5
safetensors==0.3.0
streamlit==1.20.0
streamlit-drawable-canvas==0.9.2
test-tube==0.7.5
timm==0.6.12
--pre
--extra-index-url https://download.pytorch.org/whl/nightly/cpu
torch==2.1.0.dev20230311
torchmetrics==0.11.3
torchvision==0.14.1
transformers==4.26.1
webdataset==0.2.39
yapf==0.32.0
```

if someone could get the intersection of the source `requirement.txt` and the list above that would be greaaat

<details>
	<summary>
EDIT: thanks chatgpt
	</summary>

```
albumentations==1.3.0
addict==2.4.0
basicsr==1.4.2
diffusers==0.14.0
einops==0.3.2
gradio==3.20.1
imageio==2.26.0
imageio-ffmpeg==0.4.8
kornia==0.6
langchain==0.0.101
numpy==1.23.1
omegaconf==2.1.1
opencv-contrib-python==4.4.0.46
open_clip_torch==2.0.2
pytorch-lightning==1.5.0
prettytable==3.6.0
safetensors==0.2.7
streamlit==1.12.1
streamlit-drawable-canvas==0.8.0
test-tube>=0.7.5
timmm==0.6.12
torch==1.12.1
torchmetrics==0.6.0
torchvision==0.13.1
transformers==4.26.1
webdataset==0.2.5
yapf==0.32.0
```

</details>

i'm pretty sure some of these are not necessary since i see whisperx in there but idk how to clean it up

make sure you run the `bash download.sh` script in the readme before you patch the requirements 

also make sure to `export` your OPENAI_API_KEY and `PYTORCH_ENABLE_MPS_FALLBACK=1` (temp fix for using stable diffusion on m1 macs with this pytorch imp; see below)

**Comment by sw-yx** [comment]
however now i get a `AssertionError: Torch not compiled with CUDA enabled` error 

and running this fix https://github.com/pytorch/pytorch/issues/30664#issuecomment-757431613

didnt work

**Comment by sw-yx** [comment]
i think according ot https://github.com/remixer-dec/llama-mps/commit/9a8970299bf708a86b6dfa0c115e59ea2205c0e3 you can just make it `.to('mps')`

**Comment by sw-yx** [comment]
yup it works lmao. https://twitter.com/swyxio/status/1634120614830284800

i could publish a fork if people are interested but litreally follow the insturctions above thats all i did

**Comment by whispy** [comment]
@sw-yx , in `visual_chatgpt.py`, when you say "make it to `.to('mps')`, do you mean like so:
```
        self.edit = ImageEditing.to('mps')
        self.i2t = ImageCaptioning.to('mps')
        self.t2i = T2I.to('mps')
        self.image2canny = image2canny()
        self.canny2image = canny2image.to('mps')
        self.image2line = image2line()
        self.line2image = line2image.to('mps')
        self.image2hed = image2hed()
        self.hed2image = hed2image.to('mps')
        self.image2scribble = image2scribble()
        self.scribble2image = scribble2image.to('mps')
        self.image2pose = image2pose()
        self.pose2image = pose2image.to('mps')
        self.BLIPVQA = BLIPVQA.to('mps')
        self.image2seg = image2seg()
        self.seg2image = seg2image.to('mps')
        self.image2depth = image2depth()
        self.depth2image = depth2image.to('mps')
        self.image2normal = image2normal()
        self.normal2image = normal2image.to('mps')
        self.pix2pix = Pix2Pix.to('mps')
```

Am I missing any lines? Is that how you have it?

**Comment by sw-yx** [comment]
ok was able to eliminate all errors with that simple porting strategy... but its a pretty heavy download... 

![image](https://user-images.githubusercontent.com/6764957/224289557-7c23133f-c69d-4c37-ad68-99d6ef2ca781.png)

**Comment by sw-yx** [comment]
![image](https://user-images.githubusercontent.com/6764957/224289917-86d89341-3073-435d-8fbc-27574f1f3f18.png)

it now runs but has ANOTHER runtime error lmoa

![image](https://user-images.githubusercontent.com/6764957/224289940-6a0b05bf-cf8a-48ec-83e2-d6809bf522a6.png)

**Comment by sw-yx** [comment]
there was a [large langchain memory refactor](https://github.com/hwchase17/langchain/pull/1478) in v0.0.103 - this project uses 101, i have 106. i am trying to just update it since langchain will just keep breaking stuff

**Comment by sw-yx** [comment]
```
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 997, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1
NotImplementedError: The operator 'aten::cumsum.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
````

**Comment by plong0723** [comment]
@sw-yx Excuse me, the question that size of a tensor musht match.  have been solved?

**Comment by focus000** [comment]
@sw-yx  Hi, Thx for your work. I have running web app successfully on m2 max Mac.

For stable diffusion, according to [this issue](https://github.com/pytorch/pytorch/issues/78915) just upgrade PyTorch to latest nightly will support mps topk > 16, and support for cumsum int64 was added in MacOS 13.3. 

BTW, I simplify your requirements.txt here, note that `torch` version I replaced with nightly version:
```txt
accelerate==0.17.0
addict==2.4.0
albumentations==1.3.0
basicsr==1.4.2
diffusers==0.14.0
einops==0.3.2
gradio==3.20.1
imageio==2.26.0
imageio-ffmpeg==0.4.8
invisible-watermark==0.1.5
kornia==0.6.10
langchain==0.0.106
numpy==1.23.4
omegaconf==2.3.0
openai==0.24.0
opencv-contrib-python==4.7.0.72
open-clip-torch==2.16.0
prettytable==3.6.0
pytorch-lightning==1.6.5
safetensors==0.3.0
streamlit==1.20.0
streamlit-drawable-canvas==0.9.2
test-tube==0.7.5
timm==0.6.12
torch==2.1.0.dev20230311
torchmetrics==0.11.3
torchvision==0.14.1
transformers==4.26.1
webdataset==0.2.39
yapf==0.32.0
```

**Comment by focus000** [comment]
> there was a [large langchain memory refactor](https://github.com/hwchase17/langchain/pull/1478) in v0.0.103 - this project uses 101, i have 106. i am trying to just update it since langchain will just keep breaking stuff
> 
> for now just commenting out offending line
> 
> `# self.agent.memory.buffer = cut_dialogue_history(self.agent.memory.buffer, keep_last_n_words=500)`
> 
> and replacing the buffer editing
> 
> ```python
>         # self.agent.memory.buffer = self.agent.memory.buffer + Human_prompt + 'AI: ' + AI_prompt
>         self.agent.memory.buffer.save_context({"input": Human_prompt}, {"output": AI_prompt})
> ```

should be `self.agent.memory.save_context`?

**Comment by quangogster** [comment]
@sw-yx @focus000 would you guys be able post what you have to a branch please?  Im running into countless dependencies problem despite using the latest requirements.txt

**Comment by c4rl0sm3nd3s** [comment]
which macbook m1 are you using to run this code? how many ram do you have on it? 
I am having issues running using my windows pc with RTX 2060 12gb so I was wondering if my macbook air M1 8gb will be able to handle

**Comment by gongxh13** [comment]
> @sw-yx Hi, Thx for your work. I have running web app successfully on m2 max Mac.
> 
> For stable diffusion, according to [this issue](https://github.com/pytorch/pytorch/issues/78915) just upgrade PyTorch to latest nightly will support mps topk > 16, and support for cumsum int64 was added in MacOS 13.3.
> 
> BTW, I simplify your requirements.txt here, note that `torch` version I replaced with nightly version:
> 
> ```
> accelerate==0.17.0
> addict==2.4.0
> albumentations==1.3.0
> basicsr==1.4.2
> diffusers==0.14.0
> einops==0.3.2
> gradio==3.20.1
> imageio==2.26.0
> imageio-ffmpeg==0.4.8
> invisible-watermark==0.1.5
> kornia==0.6.10
> langchain==0.0.106
> numpy==1.23.4
> omegaconf==2.3.0
> openai==0.24.0
> opencv-contrib-python==4.7.0.72
> open-clip-torch==2.16.0
> prettytable==3.6.0
> pytorch-lightning==1.6.5
> safetensors==0.3.0
> streamlit==1.20.0
> streamlit-drawable-canvas==0.9.2
> test-tube==0.7.5
> timm==0.6.12
> torch==2.1.0.dev20230311
> torchmetrics==0.11.3
> torchvision==0.14.1
> transformers==4.26.1
> webdataset==0.2.39
> yapf==0.32.0
> ```

Good

**Comment by jacobmlloyd** [comment]
> @sw-yx Hi, Thx for your work. I have running web app successfully on m2 max Mac.
> 
> For stable diffusion, according to [this issue](https://github.com/pytorch/pytorch/issues/78915) just upgrade PyTorch to latest nightly will support mps topk > 16, and support for cumsum int64 was added in MacOS 13.3.
> 
> BTW, I simplify your requirements.txt here, note that `torch` version I replaced with nightly version:
> 
> ```
> accelerate==0.17.0
> addict==2.4.0
> albumentations==1.3.0
> basicsr==1.4.2
> diffusers==0.14.0
> einops==0.3.2
> gradio==3.20.1
> imageio==2.26.0
> imageio-ffmpeg==0.4.8
> invisible-watermark==0.1.5
> kornia==0.6.10
> langchain==0.0.106
> numpy==1.23.4
> omegaconf==2.3.0
> openai==0.24.0
> opencv-contrib-python==4.7.0.72
> open-clip-torch==2.16.0
> prettytable==3.6.0
> pytorch-lightning==1.6.5
> safetensors==0.3.0
> streamlit==1.20.0
> streamlit-drawable-canvas==0.9.2
> test-tube==0.7.5
> timm==0.6.12
> torch==2.1.0.dev20230311
> torchmetrics==0.11.3
> torchvision==0.14.1
> transformers==4.26.1
> webdataset==0.2.39
> yapf==0.32.0
> ```

Can I ask how you how you got it to work with the match from there? Using the newest Nightly install I'm getting "RuntimeError: MPS does not support cumsum op with int64 input. Support has been added in macOS 13.3" On M1 Pro.

**Comment by gongxh13** [comment]
> @sw-yx Hi, Thx for your work. I have running web app successfully on m2 max Mac.
> 
> For stable diffusion, according to [this issue](https://github.com/pytorch/pytorch/issues/78915) just upgrade PyTorch to latest nightly will support mps topk > 16, and support for cumsum int64 was added in MacOS 13.3.
> 
> BTW, I simplify your requirements.txt here, note that `torch` version I replaced with nightly version:
> 
> ```
> accelerate==0.17.0
> addict==2.4.0
> albumentations==1.3.0
> basicsr==1.4.2
> diffusers==0.14.0
> einops==0.3.2
> gradio==3.20.1
> imageio==2.26.0
> imageio-ffmpeg==0.4.8
> invisible-watermark==0.1.5
> kornia==0.6.10
> langchain==0.0.106
> numpy==1.23.4
> omegaconf==2.3.0
> openai==0.24.0
> opencv-contrib-python==4.7.0.72
> open-clip-torch==2.16.0
> prettytable==3.6.0
> pytorch-lightning==1.6.5
> safetensors==0.3.0
> streamlit==1.20.0
> streamlit-drawable-canvas==0.9.2
> test-tube==0.7.5
> timm==0.6.12
> torch==2.1.0.dev20230311
> torchmetrics==0.11.3
> torchvision==0.14.1
> transformers==4.26.1
> webdataset==0.2.39
> yapf==0.32.0
> ```

Why I can not found your torch version?
```
ERROR: Could not find a version that satisfies the requirement torch==2.1.0.dev20230311 (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch==2.1.0.dev20230311
```

**Comment by focus000** [comment]
@jacobmlloyd my apologies for that, it seems mps support cumsum op still not work on macos13.3. lately I use cpu on `T2I`, and it works. I have modified following code:
```python
visual_chatgpt.py:806 : self.t2i = T2I(device="cpu")
visual_chatgpt.py:190 : self.pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float32)
```
and now the web app can generate image
<img width="559" alt="image" src="https://user-images.githubusercontent.com/7610258/224538094-9075d96e-34c1-465e-ad22-5a0b4488ae58.png">

**Comment by focus000** [comment]
@gongxh13 please use the newer version

**Comment by kelvenlaw** [comment]
@sw-yx @focus000 Thank you for help! I run it in my macbook pro m1, but I meet a problem now! when I set the device=mps, it always make a exception: 
Action: Generate Image From User Input Text
Action Input: TifaSetting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/luowentao/Documents/Source/python/visual-chatgpt-googlecolab/visual_chatgpt.py", line 908, in run_text
    res = self.agent({"input": text})
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/langchain/chains/base.py", line 168, in __call__
    raise e
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/langchain/chains/base.py", line 165, in __call__
    outputs = self._call(inputs)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/langchain/agents/agent.py", line 503, in _call
    next_step_output = self._take_next_step(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/langchain/agents/agent.py", line 420, in _take_next_step
    observation = tool.run(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/langchain/tools/base.py", line 71, in run
    raise e
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/langchain/tools/base.py", line 68, in run
    observation = self._run(tool_input)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/langchain/agents/tools.py", line 17, in _run
    return self.func(tool_input)
  File "/Users/luowentao/Documents/Source/python/visual-chatgpt-googlecolab/visual_chatgpt.py", line 198, in inference
    refined_text = self.text_refine_gpt2_pipe(text)[0]["generated_text"]
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/pipelines/text_generation.py", line 210, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/pipelines/base.py", line 1084, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/pipelines/base.py", line 1091, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/pipelines/base.py", line 992, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/pipelines/text_generation.py", line 252, in _forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.sample(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/generation/utils.py", line 2443, in sample
    outputs = self(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1043, in forward
    transformer_outputs = self.transformer(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 887, in forward
    outputs = block(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 388, in forward
    attn_outputs = self.attn(
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 310, in forward
    query, key, value = self.c_attn(hidden_states).split(self.split_size, dim=2)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/luowentao/opt/anaconda3/envs/visgpt/lib/python3.9/site-packages/transformers/pytorch_utils.py", line 115, in forward
    x = torch.addmm(self.bias, x.view(-1, x.size(-1)), self.weight)
RuntimeError: tensors must be 2-D
======

**Comment by kelvenlaw** [comment]
@sw-yx @focus000 Thank you for help! I run it in my macbook pro m1, but I meet a problem now! when I set the device=mps, it always make a exception:
`Action: Generate Image From User Input Text
Action Input: TifaSetting pad_token_id to eos_token_id:50256 for open-end generation.
....
RuntimeError: tensors must be 2-D`
When I run it in cpu, it will execute but run slowly!
======
Do you meet the error? And how can I fix it? Thank you very much!

**Comment by kelvenlaw** [comment]
@sw-yx @focus000 Thank you for help! I run it in my macbook pro m1, but I meet a problem now! when I set the device=mps, it always make a exception:
Action: Generate Image From User Input Text Action Input: TifaSetting pad_token_id to eos_token_id:50256 for open-end generation. 
.... 
RuntimeError: tensors must be 2-D
When I run it in cpu, it will execute but run slowly!
Do you meet the error? And how can I fix it? Thank you very much!

**Comment by reverie-dev** [comment]
> self.edit = ImageEditing.to('mps')
>         self.i2t = ImageCaptioning.to('mps')
>         self.t2i = T2I.to('mps')
>         self.image2canny = image2canny()
>         self.canny2image = canny2image.to('mps')
>         self.image2line = image2line()
>         self.line2image = line2image.to('mps')
>         self.image2hed = image2hed()
>         self.hed2image = hed2image.to('mps')
>         self.image2scribble = image2scribble()
>         self.scribble2image = scribble2image.to('mps')
>         self.image2pose = image2pose()
>         self.pose2image = pose2image.to('mps')
>         self.BLIPVQA = BLIPVQA.to('mps')
>         self.image2seg = image2seg()
>         self.seg2image = seg2image.to('mps')
>         self.image2depth = image2depth()
>         self.depth2image = depth2image.to('mps')
>         self.image2normal = image2normal()
>         self.normal2image = normal2image.to('mps')
>         self.pix2pix = Pix2Pix.to('mps')

AttributeError: type object 'ImageEditing' has no attribute 'to'

**Comment by jordankeyton** [comment]
### Summary of changes you need to make it work:

#### 1. Use @sw-yx 's version of the requirements 

> ```
> albumentations==1.3.0
> addict==2.4.0
> basicsr==1.4.2
> diffusers==0.14.0
> einops==0.3.2
> gradio==3.20.1
> imageio==2.26.0
> imageio-ffmpeg==0.4.8
> kornia==0.6
> langchain==0.0.101
> numpy==1.23.1
> omegaconf==2.1.1
> opencv-contrib-python==4.4.0.46
> open_clip_torch==2.0.2
> pytorch-lightning==1.5.0
> prettytable==3.6.0
> safetensors==0.2.7
> streamlit==1.12.1
> streamlit-drawable-canvas==0.8.0
> test-tube>=0.7.5
> timmm==0.6.12
> torch==1.12.1
> torchmetrics==0.6.0
> torchvision==0.13.1
> transformers==4.26.1
> webdataset==0.2.5
> yapf==0.32.0
> ```
> i'm pretty sure some of these are not necessary since i see whisperx in there but idk how to clean it up
> 
> make sure you run the `bash download.sh` script in the readme before you patch the requirements
> 
> also make sure to `export` your OPENAI_API_KEY and `PYTORCH_ENABLE_MPS_FALLBACK=1` (temp fix for using stable diffusion on m1 macs with this pytorch imp; see below)

#### 2. Make the changes in these files (Thanks again @sw-yx )


> Edit: welp another problem: `image2line()` calls `MLSDdetector()` which is cuda only
> 
> diving into the source `Controlnet/annotator/mlsd/__init__.py` i think you have to change `self.model = model.cuda().eval()` to `self.model = model.to('mps').eval()`. (learned from [this controlnet PR](https://github.com/lllyasviel/ControlNet/pull/71/files), chatgpt or perplexity were useless for this)
> 
> this seems to work
> 
> then you also do it for:
> 
> * `/ControlNet/annotator/hed/__init__.py:103`: `self.netNetwork = Network(modelpath).to('mps').eval()`
>   
>   * and `image_hed = torch.from_numpy(input_image).float().to('mps')`
> * `/ControlNet/annotator/uniformer/__init__.py:18`: `self.model = init_segmentor(config_file, modelpath, 'mps')`
> * `/ControlNet/annotator/midas/__init__.py:11`: `self.model = MiDaSInference(model_type="dpt_hybrid").to('mps')`
>   
>   * `image_depth = torch.from_numpy(image_depth).float().to('mps')`
> * `/ControlNet/cldm/ddim_hacked.py`, line 20: `attr = attr.to(torch.device("mps"))`
> 
> as well

#### 3. Change this block  in lines 804-824 in visual_chatgpt.py

> 
> 
> ```python
>         self.edit = ImageEditing(device="mps")
>         self.i2t = ImageCaptioning(device="mps")
>         self.t2i = T2I(device="cpu")
>         self.image2canny = image2canny()
>         self.canny2image = canny2image(device="mps")
>         self.image2line = image2line()
>         self.line2image = line2image(device="mps")
>         self.image2hed = image2hed()
>         self.hed2image = hed2image(device="mps")
>         self.image2scribble = image2scribble()
>         self.scribble2image = scribble2image(device="mps")
>         self.image2pose = image2pose()
>         self.pose2image = pose2image(device="mps")
>         self.BLIPVQA = BLIPVQA(device="mps")
>         self.image2seg = image2seg()
>         self.seg2image = seg2image(device="mps")
>         self.image2depth = image2depth()
>         self.depth2image = depth2image(device="mps")
>         self.image2normal = image2normal()
>         self.normal2image = normal2image(device="mps")
>         self.pix2pix = Pix2Pix(device="mps")
> ```
> 
> Edit: as indicated by @focus000 you need to run T2I on cpu. Make sure to change line 190 to float32.

#### 4. Change line 190 in visual_chatgpt.py

>it seems mps support cumsum op still not work on macos13.3. lately I use cpu on `T2I`, and it works. I have modified following code:
> 
> ```python
> visual_chatgpt.py:806 : self.t2i = T2I(device="cpu")
> visual_chatgpt.py:190 : self.pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float32)
> ```
> 
> and now the web app can generate image 


#### 5. Run the py file and question if it was worth all the effort lol

**Comment by wastu01** [comment]
Got to try it on MacOS M1 version 13.2
Looks like need to change package version
看起來是要修改 visual-chatgpt/requirement.txt 的樣子？

**Comment by wastu01** [comment]
pull the code and try again

**Comment by wastu01** [comment]
did not work and get this problem same below
https://github.com/microsoft/visual-chatgpt/issues/187

**Comment by Omaraldarwish** [comment]
what bash script are you guys talking about, can't find it in the repo!

**Comment by sw-yx** [comment]
it was removed https://github.com/microsoft/visual-chatgpt/commit/feb5dad2514f36b61a34fe805b39df4db7298410

i expect the instructions here to break further over time, im done playing with this repo, pls file other issues u need

**Comment by taohaowei** [comment]
> ### Summary of changes you need to make it work:
> #### 1. Use @sw-yx 's version of the requirements
> > ```
> > albumentations==1.3.0
> > addict==2.4.0
> > basicsr==1.4.2
> > diffusers==0.14.0
> > einops==0.3.2
> > gradio==3.20.1
> > imageio==2.26.0
> > imageio-ffmpeg==0.4.8
> > kornia==0.6
> > langchain==0.0.101
> > numpy==1.23.1
> > omegaconf==2.1.1
> > opencv-contrib-python==4.4.0.46
> > open_clip_torch==2.0.2
> > pytorch-lightning==1.5.0
> > prettytable==3.6.0
> > safetensors==0.2.7
> > streamlit==1.12.1
> > streamlit-drawable-canvas==0.8.0
> > test-tube>=0.7.5
> > timmm==0.6.12
> > torch==1.12.1
> > torchmetrics==0.6.0
> > torchvision==0.13.1
> > transformers==4.26.1
> > webdataset==0.2.5
> > yapf==0.32.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i'm pretty sure some of these are not necessary since i see whisperx in there but idk how to clean it up
> > make sure you run the `bash download.sh` script in the readme before you patch the requirements
> > also make sure to `export` your OPENAI_API_KEY and `PYTORCH_ENABLE_MPS_FALLBACK=1` (temp fix for using stable diffusion on m1 macs with this pytorch imp; see below)
> 
> #### 2. Make the changes in these files (Thanks again @sw-yx )
> > Edit: welp another problem: `image2line()` calls `MLSDdetector()` which is cuda only
> > diving into the source `Controlnet/annotator/mlsd/__init__.py` i think you have to change `self.model = model.cuda().eval()` to `self.model = model.to('mps').eval()`. (learned from [this controlnet PR](https://github.com/lllyasviel/ControlNet/pull/71/files), chatgpt or perplexity were useless for this)
> > this seems to work
> > then you also do it for:
> > 
> > * `/ControlNet/annotator/hed/__init__.py:103`: `self.netNetwork = Network(modelpath).to('mps').eval()`
> >   
> >   * and `image_hed = torch.from_numpy(input_image).float().to('mps')`
> > * `/ControlNet/annotator/uniformer/__init__.py:18`: `self.model = init_segmentor(config_file, modelpath, 'mps')`
> > * `/ControlNet/annotator/midas/__init__.py:11`: `self.model = MiDaSInference(model_type="dpt_hybrid").to('mps')`
> >   
> >   * `image_depth = torch.from_numpy(image_depth).float().to('mps')`
> > * `/ControlNet/cldm/ddim_hacked.py`, line 20: `attr = attr.to(torch.device("mps"))`
> > 
> > as well
> 
> #### 3. Change this block in lines 804-824 in visual_chatgpt.py
> > ```python
> >         self.edit = ImageEditing(device="mps")
> >         self.i2t = ImageCaptioning(device="mps")
> >         self.t2i = T2I(device="cpu")
> >         self.image2canny = image2canny()
> >         self.canny2image = canny2image(device="mps")
> >         self.image2line = image2line()
> >         self.line2image = line2image(device="mps")
> >         self.image2hed = image2hed()
> >         self.hed2image = hed2image(device="mps")
> >         self.image2scribble = image2scribble()
> >         self.scribble2image = scribble2image(device="mps")
> >         self.image2pose = image2pose()
> >         self.pose2image = pose2image(device="mps")
> >         self.BLIPVQA = BLIPVQA(device="mps")
> >         self.image2seg = image2seg()
> >         self.seg2image = seg2image(device="mps")
> >         self.image2depth = image2depth()
> >         self.depth2image = depth2image(device="mps")
> >         self.image2normal = image2normal()
> >         self.normal2image = normal2image(device="mps")
> >         self.pix2pix = Pix2Pix(device="mps")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Edit: as indicated by @focus000 you need to run T2I on cpu. Make sure to change line 190 to float32.
> 
> #### 4. Change line 190 in visual_chatgpt.py (thanks @focus000 )
> > it seems mps support cumsum op still not work on macos13.3. lately I use cpu on `T2I`, and it works. I have modified following code:
> > ```python
> > visual_chatgpt.py:806 : self.t2i = T2I(device="cpu")
> > visual_chatgpt.py:190 : self.pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float32)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and now the web app can generate image
> 
> #### 5. Run the py file and question if it was worth all the effort lol

warn：timmm has an extra m

**Comment by wastu01** [comment]
> i can now get the webapp running but basically every command i try results in an error.
> 
> ![image](https://user-images.githubusercontent.com/6764957/224297882-ed99b25c-7884-485e-bb7e-a829da8c29da.png)
> 
> ## for stable diffusion
> have to say `generate _____` as your instruction or it will infer the wrong intent.
> 
> make sure to `export PYTORCH_ENABLE_MPS_FALLBACK=1` to deal with below
> 
> ```
>   File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 997, in prepare_inputs_for_generation
>     position_ids = attention_mask.long().cumsum(-1) - 1
> NotImplementedError: The operator 'aten::cumsum.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
> ```
> 
> however it runs into
> 
> ```
>  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 297, in __call__
>     indices_to_remove = scores < torch.topk(scores, top_k)[0][..., -1, None]
> RuntimeError: Currently topk on mps works only for k<=16
> ```
> 
> ## for masking
> currently facing this crap
> 
> ![image](https://user-images.githubusercontent.com/6764957/224298062-c8150eeb-f5e3-4422-a0aa-6affff2ebd4d.png)
> 
> ## for pix2pix
> "make it look like a painting"
> 
> seems to work tho not suuuper well
> 
> ![image](https://user-images.githubusercontent.com/6764957/224299114-98bf8998-25c5-4b74-8dd0-c95b0738b673.png)
> 
> ## image 2 text
> works but sucks
> 
> ![image](https://user-images.githubusercontent.com/6764957/224299385-aebf273a-f420-41b4-b9e9-d61b12baafda.png)
> 
> ## BLIPVQA
> ![image](https://user-images.githubusercontent.com/6764957/224299702-953d2d9b-54ea-4f60-8d30-3741c91461bb.png)
> 
> ## edge detection
> ![image](https://user-images.githubusercontent.com/6764957/224299777-2a3cd9c6-caa2-4091-b558-bce9a6b7797a.png)
> 
> ## pose2image

btw I use it for changing Clothes

https://hackmd.io/@DCT/Microsoft-Visual-ChatGPT
