### ISSUE TITLE
Unresolved reference ‘ControlNet’

### ISSUE THREAD

**Issue by 77LJH** [microsoft/visual-chatgpt#46]
After I forked your code, I found that PyCharm prompted ‘Unresolved reference ‘ControlNet’’, what should I do?

**Comment by andzejsp** [comment]
linux or windows?

on windows i had to clone the controlnet repo manually. see my installscript for some idea.
#43 

and if that dont work maybe the problem is somewhere else

**Comment by K-tang-mkv** [comment]
@77LJH make sure each step you're right, please provide more detail about your error. Have u ever download the ControlNet?
