### ISSUE TITLE
 GPU memory usage of each VFM module.

### ISSUE THREAD

**Issue by hjbiao09** [microsoft/visual-chatgpt#5]
First of all, thank you for sharing this amazing method.
After checking the code briefly, it seems that to use various VFM modules, they need to be allocated to multiple GPUs first.
If you could explain the GPU usage of each VFM module on the page, users would be able to make choices on VFMS based on their  environment.

**Comment by Wang-Xiaodong1899** [comment]
Thank you for your advice. You can choose which models you want to load on your cuda devices, but not always all of them. You can modify self.tools with fewer Tools to save your GPU memory. We'll count the GPU memory usage of each VFM later.

Thanks again!
