### ISSUE TITLE
请问怎么在pycharm中设置open_ai_key，从而让程序成功运行？

### ISSUE THREAD

**Issue by IssacaLaw** [microsoft/visual-chatgpt#57]
ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable 
`OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named 
parameter. (type=value_error)

**Comment by IssacaLaw** [comment]
在win10中添加环境变量，仍然显示如上错误
![image](https://user-images.githubusercontent.com/71266344/224460929-b61c5771-e9f6-4ba6-ae75-6c9544ddd998.png)

**Comment by ATang0729** [comment]
It has been mentioned in `readme.md`, you should enter `export OPENAI_API_KEY={Your_Private_Openai_Key}` in you terminal

you can get `OPENAI_API_KEY` under the [guidance](https://help.openai.com/en/articles/4936850-where-do-i-find-my-secret-api-key)

**Comment by FunnySaltyFish** [comment]
If you are using Linux, just use `export`; if you are using windows, you can set environment variable by searching "环境变量" and editing it. Or maybe you can try `python-dotenv`,  you can refer to [this blog](https://blog.csdn.net/qq_24487005/article/details/123803313) to add some codes to load custom env vars.

**Comment by ATang0729** [comment]
> If you are using Linux, just use `export`; if you are using windows, you can set environment variable by searching "环境变量" and editing it. Or maybe you can try `python-dotenv`, you can refer to [this blog](https://blog.csdn.net/qq_24487005/article/details/123803313) to add some codes to load custom env vars.

if you are using windows, just change `export` to `set` (i.e. use `set OPENAI_API_KEY={Your_Private_Openai_Key}`)

**Comment by IssacaLaw** [comment]
> > 如果您使用的是 Linux，只需使用`export`; 如果你使用的是windows，你可以通过搜索“环境变量”并编辑它来设置环境变量。或者你可以试试`python-dotenv`，你可以参考[这篇博客](https://blog.csdn.net/qq_24487005/article/details/123803313)添加一些代码来加载自定义环境变量。
> 
> 如果您使用的是 Windows，只需更改`export`为`set`（即使用`set OPENAI_API_KEY={Your_Private_Openai_Key}`）

thx,solved the problem
