### ISSUE TITLE
Why do I keep stopping at "entering new agent executor chin.." ?

### ISSUE THREAD

**Issue by XXXKAY** [microsoft/visual-chatgpt#67]

**Comment by CODINNLG** [comment]
Hi, you should open the graphical interface through the URL for interactive operation since our system is implemented based on the ``gradio``.

**Comment by liuicheng123** [comment]
@CODINNLG @XXXKAY 
Hello, I also encountered this problem. I can't solve it by mapping to local via ssh.
I have mapped the port of the server to the local computer through ssh. I can access the port of the server through the browser and see the interface of the video. But I found that the problem is that my openai interface has not been called. What is the reason.

**Comment by XXXKAY** [comment]
> Hi, you should open the graphical interface through the URL for interactive operation since our system is implemented based on the `gradio`.

Thank you for your reply, but I've actually opened the GUI in my browser and when I type prompt it just keeps showing "entering new agent executor chin.."

**Comment by XXXKAY** [comment]
> @CODINNLG @XXXKAY Hello, I also encountered this problem. I can't solve it by mapping to local via ssh. I have mapped the port of the server to the local computer through ssh. I can access the port of the server through the browser and see the interface of the video. But I found that the problem is that my openai interface has not been called. What is the reason.

I have the same problem as you. I haven't solved it yet

**Comment by IssacaLaw** [comment]
> > @CODINNLG @XXXKAY你好，我也遇到了这个问题。我无法通过ssh映射到本地来解决它。我已经通过ssh把服务器的端口映射到了本地电脑。我可以通过浏览器访问服务器的端口，看到视频的界面。但是我发现问题是我的openai接口一直没有被调用。是什么原因。
> 
> 我和你有同样的问题。我还没解决
我也一样，你解决了吗

**Comment by wrk226** [comment]
Same here, I guess it's because of poor network connection, so that the code is unable to call the ChatGPT API successfully.

**Comment by YeHaijia** [comment]
+1

**Comment by XXXKAY** [comment]
我已经解决这个问题了原因是我所在地区访问openai的api受限,解决方案终端指定一下代理

I have solved this problem due to the limited api access to openai in my area, and the solution terminal specifies the proxy
